/**
 * Massa de dados fictícios para validação visual do Workspace (Sprint 006.5 + Sprint 007).
 * Usados como fallback quando o Supabase não retorna dados em ambiente de desenvolvimento.
 */

import {
  UIConversation,
  UIMessage,
  MessageDirection,
  MessageType,
  ClientMemory,
  Contact,
  Deal,
  Appointment,
  TeamMember,
  Person,
  Company,
  Task,
  TimelineEntry,
  ChannelType,
} from '@/types';

// ──────────────────────────────────────────────
// HELPERS
// ──────────────────────────────────────────────

const t = (h: number, m: number): string =>
  `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;

const av = (name: string, bg = '0ea5e9'): string =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=fff`;

type FromType = 'user' | 'nina' | 'human';

const msg = (
  id: string,
  content: string,
  hour: number,
  min: number,
  from: FromType,
  status: 'read' | 'delivered' | 'sent' = 'read',
  channel?: ChannelType
): UIMessage => ({
  id,
  content,
  timestamp: t(hour, min),
  direction: from === 'user' ? MessageDirection.INCOMING : MessageDirection.OUTGOING,
  type: MessageType.TEXT,
  status,
  fromType: from,
  mediaUrl: null,
  whatsappMessageId: null,
  channel,
});

const mem = (
  stage: string,
  score: number,
  interests: string[],
  objections: string[],
  products: string[],
  style: string,
  painPoints: string[],
  nextAction: string,
  budget: string,
  timeline: string,
  responsePattern: string,
  lastReason: string,
  totalConvs: number,
  prefTime: string
): ClientMemory => ({
  last_updated: '2026-07-01T08:00:00.000Z',
  lead_profile: {
    interests,
    lead_stage: stage,
    objections,
    products_discussed: products,
    communication_style: style,
    qualification_score: score,
  },
  sales_intelligence: {
    pain_points: painPoints,
    next_best_action: nextAction,
    budget_indication: budget,
    decision_timeline: timeline,
  },
  interaction_summary: {
    response_pattern: responsePattern,
    last_contact_reason: lastReason,
    total_conversations: totalConvs,
    preferred_contact_time: prefTime,
  },
  conversation_history: [],
});

// ──────────────────────────────────────────────
// TEAM MEMBERS
// ──────────────────────────────────────────────

export const MOCK_TEAM_EXTENDED: TeamMember[] = [
  {
    id: 'tm1',
    name: 'Admin User',
    email: 'admin@integraconnect.com.br',
    role: 'admin',
    status: 'active',
    avatar: av('Admin User', '0891b2'),
    lastActive: 'Agora',
  },
  {
    id: 'tm2',
    name: 'Sarah Connor',
    email: 'sarah@integraconnect.com.br',
    role: 'manager',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?u=sarah_ic',
    lastActive: 'Há 3 min',
  },
  {
    id: 'tm3',
    name: 'Bruno Carvalho',
    email: 'bruno@integraconnect.com.br',
    role: 'agent',
    status: 'active',
    avatar: av('Bruno Carvalho', '7c3aed'),
    lastActive: 'Há 10 min',
  },
  {
    id: 'tm4',
    name: 'Patrícia Rocha',
    email: 'patricia@integraconnect.com.br',
    role: 'agent',
    status: 'active',
    avatar: av('Patricia Rocha', 'db2777'),
    lastActive: 'Há 22 min',
  },
  {
    id: 'tm5',
    name: 'Felipe Mendonça',
    email: 'felipe@integraconnect.com.br',
    role: 'agent',
    status: 'active',
    avatar: av('Felipe Mendonca', 'ea580c'),
    lastActive: 'Há 5 min',
  },
  {
    id: 'tm6',
    name: 'Carla Dias',
    email: 'carla@integraconnect.com.br',
    role: 'agent',
    status: 'active',
    avatar: av('Carla Dias', '16a34a'),
    lastActive: 'Há 45 min',
  },
];

// ──────────────────────────────────────────────
// CONTACTS (para a página de Contatos)
// ──────────────────────────────────────────────

export const MOCK_CONTACTS_EXTENDED: Contact[] = [
  { id: 'ct1', name: 'João Silva', phone: '+55 11 98432-1567', email: 'joao.silva@contabilidade.com.br', status: 'lead', lastContact: '01/07/2026' },
  { id: 'ct2', name: 'Maria Oliveira', phone: '+55 11 97654-3210', email: 'maria@oliveiracorp.com.br', status: 'customer', lastContact: '01/07/2026' },
  { id: 'ct3', name: 'Carlos Mendes', phone: '+55 11 96789-4532', email: 'carlosmendes@construtora.com.br', status: 'lead', lastContact: '01/07/2026' },
  { id: 'ct4', name: 'Fernanda Costa', phone: '+55 11 95678-2341', email: 'fernanda@costadvocacia.com.br', status: 'customer', lastContact: '30/06/2026' },
  { id: 'ct5', name: 'Pedro Santos', phone: '+55 11 94523-8765', email: 'pedro@santospremium.com.br', status: 'customer', lastContact: '01/07/2026' },
  { id: 'ct6', name: 'Clínica Vida Plena', phone: '+55 11 3456-7890', email: 'contato@vidaplena.med.br', status: 'lead', lastContact: '01/07/2026' },
  { id: 'ct7', name: 'Lumina Iluminação', phone: '+55 11 3234-5678', email: 'comercial@luminailuminacao.com.br', status: 'lead', lastContact: '29/06/2026' },
  { id: 'ct8', name: 'Ricardo Almeida', phone: '+55 11 93456-7890', email: 'ricardo.almeida@consultoria.com', status: 'customer', lastContact: '01/07/2026' },
  { id: 'ct9', name: 'Ana Souza', phone: '+55 11 92345-6789', email: 'ana.souza@minhaloja.com.br', status: 'lead', lastContact: '01/07/2026' },
  { id: 'ct10', name: 'Juliana Martins', phone: '+55 11 91234-5678', email: 'juliana@farmaciasunidas.com.br', status: 'lead', lastContact: '01/07/2026' },
];

// ──────────────────────────────────────────────
// DEALS (para o Kanban)
// ──────────────────────────────────────────────

export const MOCK_DEALS_EXTENDED: Deal[] = [
  {
    id: 'dl1',
    title: 'Automação de Atendimento',
    company: 'Contabilidade João Silva',
    value: 4764,
    stage: 'qualification',
    stageId: 'qualification',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Novo Lead', 'Contabilidade'],
    dueDate: '2026-07-05',
    priority: 'high',
    contactId: 'ct1',
    contactName: 'João Silva',
    contactPhone: '+55 11 98432-1567',
    contactEmail: 'joao.silva@contabilidade.com.br',
  },
  {
    id: 'dl2',
    title: 'Suporte Premium Anual',
    company: 'Oliveira Corp',
    value: 5964,
    stage: 'won',
    stageId: 'won',
    ownerAvatar: av('Bruno Carvalho', '7c3aed'),
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    tags: ['Cliente', 'Renovação'],
    priority: 'medium',
    contactId: 'ct2',
    contactName: 'Maria Oliveira',
    contactPhone: '+55 11 97654-3210',
    contactEmail: 'maria@oliveiracorp.com.br',
    wonAt: '2026-06-28T14:00:00.000Z',
  },
  {
    id: 'dl3',
    title: 'Plano Corporativo Business',
    company: 'Construtora Mendes',
    value: 19200,
    stage: 'negotiation',
    stageId: 'negotiation',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Enterprise', 'Hot Lead'],
    dueDate: '2026-07-10',
    priority: 'high',
    contactId: 'ct3',
    contactName: 'Carlos Mendes',
    contactPhone: '+55 11 96789-4532',
  },
  {
    id: 'dl4',
    title: 'Integração WhatsApp Business',
    company: 'Fernanda Costa Advocacia',
    value: 2388,
    stage: 'won',
    stageId: 'won',
    ownerAvatar: av('Carla Dias', '16a34a'),
    ownerId: 'tm6',
    ownerName: 'Carla Dias',
    tags: ['Jurídico', 'Onboarding'],
    priority: 'medium',
    contactId: 'ct4',
    contactName: 'Fernanda Costa',
    contactPhone: '+55 11 95678-2341',
    wonAt: '2026-06-30T09:41:00.000Z',
  },
  {
    id: 'dl5',
    title: 'Renovação Contrato VIP',
    company: 'Santos Premium Group',
    value: 14400,
    stage: 'negotiation',
    stageId: 'negotiation',
    ownerAvatar: av('Patricia Rocha', 'db2777'),
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    tags: ['VIP', 'Renovação', 'Em Risco'],
    dueDate: '2026-07-01',
    priority: 'high',
    contactId: 'ct5',
    contactName: 'Pedro Santos',
    contactPhone: '+55 11 94523-8765',
  },
  {
    id: 'dl6',
    title: 'Plano Saúde — Clínica Multidisciplinar',
    company: 'Clínica Vida Plena',
    value: 8964,
    stage: 'presentation',
    stageId: 'presentation',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Saúde', 'Demo Agendada'],
    dueDate: '2026-07-03',
    priority: 'medium',
    contactId: 'ct6',
    contactName: 'Clínica Vida Plena',
    contactPhone: '+55 11 3456-7890',
  },
  {
    id: 'dl7',
    title: 'Integração SAP + WhatsApp',
    company: 'Lumina Iluminação',
    value: 28800,
    stage: 'presentation',
    stageId: 'presentation',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Enterprise', 'SAP', 'Proposta Enviada'],
    dueDate: '2026-07-08',
    priority: 'high',
    contactId: 'ct7',
    contactName: 'Lumina Iluminação',
    contactPhone: '+55 11 3234-5678',
  },
  {
    id: 'dl8',
    title: 'Contrato de Retenção',
    company: 'Ricardo Almeida Consultoria',
    value: 3588,
    stage: 'negotiation',
    stageId: 'negotiation',
    ownerAvatar: av('Patricia Rocha', 'db2777'),
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    tags: ['Retenção', 'Urgente'],
    dueDate: '2026-07-15',
    priority: 'high',
    contactId: 'ct8',
    contactName: 'Ricardo Almeida',
    contactPhone: '+55 11 93456-7890',
  },
  {
    id: 'dl9',
    title: 'Plano Starter — E-commerce',
    company: 'Ana Souza — Minha Loja',
    value: 2364,
    stage: 'qualification',
    stageId: 'qualification',
    ownerAvatar: av('Bruno Carvalho', '7c3aed'),
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    tags: ['E-commerce', 'Lead Frio'],
    dueDate: '2026-07-20',
    priority: 'low',
    contactId: 'ct9',
    contactName: 'Ana Souza',
    contactPhone: '+55 11 92345-6789',
  },
  {
    id: 'dl10',
    title: 'Plano Multi-Unidade — 8 Farmácias',
    company: 'Farmácias Unidas Martins',
    value: 33600,
    stage: 'negotiation',
    stageId: 'negotiation',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Enterprise', 'Hot Lead', 'Indicação'],
    dueDate: '2026-07-01',
    priority: 'high',
    contactId: 'ct10',
    contactName: 'Juliana Martins',
    contactPhone: '+55 11 91234-5678',
  },
  {
    id: 'dl11',
    title: 'Chatbot IA — Imobiliária',
    company: 'Imóveis Central SP',
    value: 7188,
    stage: 'new',
    stageId: 'new',
    ownerAvatar: av('Bruno Carvalho', '7c3aed'),
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    tags: ['Imobiliário', 'Novo'],
    dueDate: '2026-07-25',
    priority: 'medium',
    contactName: 'Rafael Nunes',
    contactPhone: '+55 11 98765-4321',
  },
  {
    id: 'dl12',
    title: 'Automação Financeira',
    company: 'Fintech Crédito Rápido',
    value: 15600,
    stage: 'lost',
    stageId: 'lost',
    ownerAvatar: av('Carla Dias', '16a34a'),
    ownerId: 'tm6',
    ownerName: 'Carla Dias',
    tags: ['Fintech', 'Perdido'],
    priority: 'medium',
    contactName: 'Marcos Figueiredo',
    lostAt: '2026-06-25T16:00:00.000Z',
    lostReason: 'Optou por solução concorrente com maior integração bancária.',
  },
];

// ──────────────────────────────────────────────
// APPOINTMENTS
// ──────────────────────────────────────────────

const today = new Date();
const dy = (offset: number) =>
  new Date(today.getFullYear(), today.getMonth(), today.getDate() + offset)
    .toISOString()
    .split('T')[0];

export const MOCK_APPOINTMENTS_EXTENDED: Appointment[] = [
  {
    id: 'ap1',
    title: 'Demo — Clínica Vida Plena',
    date: dy(2),
    time: '15:00',
    duration: 45,
    type: 'demo',
    attendees: ['Gerente Médico', 'TI Clínica', 'Recepcionista Chefe'],
    description: 'Apresentar módulo de agendamento automático e integração com prontuário eletrônico.',
    contact_id: 'ct6',
  },
  {
    id: 'ap2',
    title: 'Follow-up — Carlos Mendes',
    date: dy(1),
    time: '15:00',
    duration: 30,
    type: 'followup',
    attendees: ['Carlos Mendes'],
    description: 'Aguardando aprovação da diretoria para o Plano Business. Verificar decisão.',
    contact_id: 'ct3',
  },
  {
    id: 'ap3',
    title: 'Reunião de Kickoff — Fernanda Costa Advocacia',
    date: dy(3),
    time: '10:00',
    duration: 60,
    type: 'meeting',
    attendees: ['Fernanda Costa', 'Carla Dias'],
    description: 'Onboarding oficial — configurar fluxos de atendimento e treinar equipe.',
    contact_id: 'ct4',
  },
  {
    id: 'ap4',
    title: 'Demo — João Silva',
    date: dy(1),
    time: '14:00',
    duration: 60,
    type: 'demo',
    attendees: ['João Silva'],
    description: 'Demonstração do Plano Profissional com integração ContaAzul.',
    contact_id: 'ct1',
  },
  {
    id: 'ap5',
    title: 'Reunião de Fechamento — Lumina Iluminação',
    date: dy(7),
    time: '14:00',
    duration: 60,
    type: 'meeting',
    attendees: ['Diretor Comercial', 'TI Lumina', 'Felipe Mendonça'],
    description: 'Apresentar contrato ajustado com SLA 99,9% e relatório por departamento.',
    contact_id: 'ct7',
  },
  {
    id: 'ap6',
    title: 'Check-in Retenção — Ricardo Almeida',
    date: dy(0),
    time: '11:00',
    duration: 20,
    type: 'followup',
    attendees: ['Ricardo Almeida', 'Patrícia Rocha'],
    description: 'Monitoramento diário após compromisso de 15 dias de experiência sem erros.',
    contact_id: 'ct8',
  },
  {
    id: 'ap7',
    title: 'Negociação Final — Farmácias Unidas',
    date: dy(0),
    time: '16:00',
    duration: 45,
    type: 'meeting',
    attendees: ['Juliana Martins', 'Felipe Mendonça', 'Sarah Connor'],
    description: 'Decisão final sobre desconto de 15% no plano anual para 8 unidades.',
    contact_id: 'ct10',
  },
];

// ──────────────────────────────────────────────
// UI CONVERSATIONS (Chat Workspace)
// ──────────────────────────────────────────────

export const MOCK_UI_CONVERSATIONS: UIConversation[] = [
  // ─── C1: João Silva — Lead novo, IA ativa, 3 mensagens não lidas ───
  {
    id: 'conv1',
    contactId: 'ct1',
    contactName: 'João Silva',
    contactPhone: '+55 11 98432-1567',
    contactAvatar: av('Joao Silva', '0369a1'),
    contactEmail: 'joao.silva@contabilidade.com.br',
    status: 'nina',
    isActive: true,
    assignedTeam: null,
    assignedUserId: 'tm5',
    assignedUserName: 'Felipe Mendonça',
    lastMessage: 'Quanto custa o plano para 3 atendentes?',
    lastMessageTime: '8min',
    unreadCount: 3,
    // Sprint 008 — unified history example: this same customer moved
    // WhatsApp -> Instagram -> Webchat -> WhatsApp; primaryChannel reflects
    // the current predominant channel while individual messages below keep
    // their own real channel (see msg() calls c1m15-c1m17).
    primaryChannel: 'whatsapp',
    tags: ['Novo Lead', 'Orçamento', 'Demo Agendada'],
    notes: 'Cliente prefere contato pela manhã. Demo agendada para amanhã às 14h. Integração com ContaAzul é pré-requisito.',
    clientMemory: mem(
      'prospect', 65,
      ['automação WhatsApp', 'CRM integrado', 'relatórios'],
      ['preço acima do esperado', 'precisa ver demo antes de decidir'],
      ['Plano Profissional', 'integração ContaAzul'],
      'objetivo e direto',
      ['volume alto de mensagens no WhatsApp', 'time pequeno sem conseguir escalar atendimento'],
      'Confirmar comparecimento da demo amanhã às 14h e enviar proposta com detalhes do plano anual.',
      'R$ 400–500/mês',
      '1–2 semanas',
      'Responde rápido durante horário comercial',
      'Pedido de orçamento e agendamento de demo',
      1, 'manhã (8h–12h)'
    ),
    messages: [
      msg('c1m01', 'Boa tarde! Vi vocês no Instagram e tenho interesse em automatizar o atendimento da minha empresa.', 9, 12, 'user'),
      msg('c1m02', 'Boa tarde, João! Que ótimo que nos encontrou 😊 Sou a Nina, assistente da Integra Connect. Me conta um pouco sobre o seu negócio — qual é o segmento e quantos atendimentos fazem por dia?', 9, 12, 'nina'),
      msg('c1m03', 'Tenho uma contabilidade com 3 atendentes. Em média umas 40 mensagens por dia no WhatsApp.', 9, 14, 'user'),
      msg('c1m04', 'Perfeito! Para o seu perfil, o Plano Profissional é o mais indicado. Ele inclui IA ativa no WhatsApp, até 5 atendentes simultâneos, relatórios e CRM integrado. Gostaria de ver uma demonstração ao vivo?', 9, 15, 'nina'),
      msg('c1m05', 'Sim, adoraria! Mas antes: vocês integram com o ContaAzul?', 9, 16, 'user'),
      msg('c1m06', 'Sim! Temos integração nativa com o ContaAzul. A configuração leva menos de 1 hora e pode ser feita remotamente.', 9, 16, 'nina'),
      msg('c1m07', 'Posso te apresentar dois horários para a demo: amanhã às 14h ou sexta-feira às 10h. Qual prefere?', 9, 17, 'nina'),
      msg('c1m08', 'Amanhã às 14h fica ótimo!', 9, 18, 'user'),
      msg('c1m09', 'Agendado! ✅ Vou confirmar pelo WhatsApp antes da reunião. Tem mais alguma dúvida?', 9, 18, 'nina'),
      msg('c1m10', 'Tem período de teste gratuito?', 9, 20, 'user'),
      msg('c1m11', 'Temos 14 dias grátis, sem cartão de crédito. Você testa todas as funcionalidades antes de decidir.', 9, 20, 'nina'),
      msg('c1m12', 'Ótimo! E quanto custa o plano anual?', 9, 21, 'user'),
      msg('c1m13', 'O Plano Profissional anual sai por R$ 397/mês (cobrado anualmente). No plano mensal fica R$ 497/mês. A maioria dos clientes prefere o anual pela economia de 20%.', 9, 21, 'nina'),
      msg('c1m14', 'Entendido. Vou pensar e te respondo depois da demo.', 9, 22, 'user'),
      msg('c1m15', 'Ah, me esqueci: tem suporte em português? (te chamei aqui pelo Instagram mesmo)', 9, 25, 'user', 'delivered', 'instagram'),
      msg('c1m16', 'E a IA responde fora do horário comercial? Testando o chat do site agora.', 9, 26, 'user', 'delivered', 'webchat'),
      msg('c1m17', 'Quanto custa o plano para 3 atendentes?', 9, 27, 'user', 'sent', 'whatsapp'),
    ],
  },

  // ─── C2: Maria Oliveira — Suporte resolvido, humano assumiu ───
  {
    id: 'conv2',
    contactId: 'ct2',
    contactName: 'Maria Oliveira',
    contactPhone: '+55 11 97654-3210',
    contactAvatar: av('Maria Oliveira', 'be185d'),
    contactEmail: 'maria@oliveiracorp.com.br',
    status: 'human',
    isActive: true,
    assignedTeam: null,
    assignedUserId: 'tm3',
    assignedUserName: 'Bruno Carvalho',
    lastMessage: 'Você também! 🙏',
    lastMessageTime: '22min',
    unreadCount: 0,
    primaryChannel: 'whatsapp',
    tags: ['Suporte', 'Cliente', 'Resolvido'],
    notes: 'Configurar renovação automática de token de WhatsApp Business a cada 90 dias. Enviado relatório dos 7 clientes afetados por email.',
    clientMemory: mem(
      'customer', 88,
      ['estabilidade de plataforma', 'suporte rápido', 'monitoramento proativo'],
      [],
      ['Plano Profissional', 'Suporte Premium'],
      'direto e profissional',
      ['instabilidade na integração WhatsApp', 'perda de atendimento fora do horário'],
      'Ativar monitoramento 24/7 automático e agendar revisão trimestral de tokens.',
      'Acima de R$ 500/mês',
      'Cliente ativo — renovação em outubro',
      'Responde no mesmo dia',
      'Falha de integração WhatsApp durante a madrugada',
      4, 'manhã (8h–10h)'
    ),
    messages: [
      msg('c2m01', 'Bom dia! Minha integração com WhatsApp caiu ontem à noite e os clientes não estão recebendo resposta.', 8, 0, 'user'),
      msg('c2m02', 'Bom dia, Maria! Entendo a urgência. Vou verificar o status da sua integração agora mesmo 🔍', 8, 1, 'nina'),
      msg('c2m03', 'Identifiquei uma instabilidade no servidor de webhook. Nossa equipe técnica já foi notificada. Posso te transferir para um especialista?', 8, 2, 'nina'),
      msg('c2m04', 'Sim, por favor! Já perdi alguns atendimentos por causa disso.', 8, 3, 'user'),
      msg('c2m05', 'Transferindo agora para Bruno, nosso especialista em integrações. Um momento!', 8, 4, 'nina'),
      msg('c2m06', 'Oi Maria! Aqui é o Bruno do suporte técnico. Já estou olhando o seu caso. Pode me passar o número WhatsApp Business com problema?', 8, 5, 'human'),
      msg('c2m07', 'É o +55 11 97654-3210. A integração parou às 23h47 de ontem.', 8, 6, 'user'),
      msg('c2m08', 'Perfeito. Encontrei o problema — houve uma desconexão no token de autenticação. Vou regenerar agora.', 8, 7, 'human'),
      msg('c2m09', 'Feito! Testei aqui e o webhook já está recebendo normalmente. Consegue testar do seu lado?', 8, 9, 'human'),
      msg('c2m10', 'Funcionou! Acabei de receber a mensagem de teste. 😊', 8, 10, 'user'),
      msg('c2m11', 'Ótimo! Para prevenir que isso aconteça novamente, vou ativar o monitoramento automático. Qualquer queda, vocês são alertados antes de perceber.', 8, 11, 'human'),
      msg('c2m12', 'Que bom! Mas como isso aconteceu? Nunca havia dado problema.', 8, 12, 'user'),
      msg('c2m13', 'Foi uma atualização da API do WhatsApp que exige renovação do token a cada 90 dias. Estou configurando a renovação automática agora.', 8, 13, 'human'),
      msg('c2m14', 'Perfeito! E os clientes que tentaram falar comigo durante a madrugada?', 8, 15, 'user'),
      msg('c2m15', 'Eles receberam uma mensagem automática informando instabilidade e prometendo retorno. Posso exportar a lista desses contatos pra você.', 8, 16, 'human'),
      msg('c2m16', 'Sim, me manda por favor!', 8, 18, 'user'),
      msg('c2m17', 'Vou preparar e te envio por email até o final da manhã. Alguma outra dúvida?', 8, 20, 'human'),
      msg('c2m18', 'Não por enquanto. Muito obrigada pelo atendimento rápido, Bruno!', 8, 22, 'user'),
      msg('c2m19', 'Disponha, Maria! Qualquer coisa pode me chamar aqui mesmo. Tenha um ótimo dia! 😊', 8, 24, 'human'),
      msg('c2m20', 'Você também! 🙏', 8, 25, 'user'),
      msg('c2m21', 'Bruno, o relatório chegou. Eram 7 clientes. Vou fazer o retorno manual. Obrigada!', 8, 43, 'user'),
      msg('c2m22', 'Perfeito! Se precisar de mais alguma coisa, estamos por aqui. 👍', 8, 45, 'human'),
    ],
  },

  // ─── C3: Carlos Mendes — Aguardando cliente, parado há 2h ───
  {
    id: 'conv3',
    contactId: 'ct3',
    contactName: 'Carlos Mendes',
    contactPhone: '+55 11 96789-4532',
    contactAvatar: av('Carlos Mendes', '92400e'),
    contactEmail: 'carlosmendes@construtora.com.br',
    status: 'paused',
    isActive: true,
    assignedTeam: null,
    assignedUserId: 'tm5',
    assignedUserName: 'Felipe Mendonça',
    lastMessage: 'Preciso confirmar com minha equipe, te retorno até amanhã.',
    lastMessageTime: '2h',
    unreadCount: 0,
    primaryChannel: 'whatsapp',
    tags: ['Aguardando Retorno', 'Proposta', 'Negociação'],
    notes: 'Sempre solicitar aprovação interna antes de gerar contrato. Reunião de fechamento agendada para quinta às 15h. Diretoria analisa o Plano Business.',
    clientMemory: mem(
      'negotiation', 72,
      ['escalada inteligente', 'supervisores inclusos', 'flexibilidade contratual'],
      ['multa rescisória', 'dúvida sobre customização pós-contrato'],
      ['Plano Business', 'Plano Corporativo'],
      'analítico e detalhista',
      ['atendimento não escalável com o crescimento da empresa', 'falta de visibilidade sobre equipe de suporte'],
      'Fazer follow-up quinta-feira às 15h para reunião de fechamento. Confirmar quórum com a diretoria.',
      'R$ 1.200–1.800/mês',
      '3–5 dias',
      'Responde rapidamente durante o dia',
      'Análise detalhada de proposta e reagendamento de reunião',
      2, 'tarde (13h–17h)'
    ),
    messages: [
      msg('c3m01', 'Olá! Recebi a proposta por email mas não consegui abrir o arquivo PDF.', 7, 30, 'user'),
      msg('c3m02', 'Olá, Carlos! Que pena. Vou reenviar em outro formato. Pode confirmar seu email?', 7, 31, 'nina'),
      msg('c3m03', 'carlosmendes@construtora.com.br', 7, 32, 'user'),
      msg('c3m04', 'Reenviado! Agora em formato Word e PDF compactado. Algum outro problema?', 7, 33, 'nina'),
      msg('c3m05', 'Chegou! Estou lendo... A proposta está bem detalhada, mas tenho dúvidas sobre o item 3.', 7, 34, 'user'),
      msg('c3m06', 'Claro! Pode me perguntar diretamente.', 7, 35, 'nina'),
      msg('c3m07', 'No item 3 fala em "atendentes ilimitados". Isso inclui supervisores também?', 7, 36, 'user'),
      msg('c3m08', 'Sim! No Plano Business, supervisores têm acesso completo e não contam nas métricas de atendentes. Eles têm dashboard próprio de gestão.', 7, 37, 'nina'),
      msg('c3m09', 'E a IA pode escalar automaticamente para um supervisor quando o cliente está insatisfeito?', 7, 38, 'user'),
      msg('c3m10', 'Exatamente! É o nosso Modo Escalada Inteligente. Quando o sentimento da conversa indica frustração, a IA notifica o supervisor em tempo real.', 7, 39, 'nina'),
      msg('c3m11', 'Gostei muito disso. Outra dúvida: o contrato é anual com multa rescisória?', 7, 41, 'user'),
      msg('c3m12', 'O contrato anual tem aviso prévio de 30 dias, sem multa após os primeiros 3 meses. Muito mais flexível que o mercado.', 7, 42, 'nina'),
      msg('c3m13', 'Entendido. Vou apresentar para minha diretoria amanhã. Posso reagendar a reunião de fechamento para quinta?', 7, 44, 'user'),
      msg('c3m14', 'Claro! Tenho disponibilidade na quinta entre 13h e 17h. Qual horário fica melhor?', 7, 45, 'nina'),
      msg('c3m15', 'Entre 14h e 16h.', 7, 46, 'user'),
      msg('c3m16', 'Perfeito! Agendado para quinta às 15h. Nosso executivo de contas enviará o convite. Mais alguma dúvida?', 7, 47, 'nina'),
      msg('c3m17', 'Posso customizar os fluxos de atendimento depois do contrato assinado?', 7, 48, 'user'),
      msg('c3m18', 'Sim! Após a assinatura, você tem 30 dias de onboarding guiado. Todos os fluxos são totalmente customizáveis.', 7, 49, 'nina'),
      msg('c3m19', 'Preciso confirmar com minha equipe, te retorno até amanhã.', 7, 51, 'user'),
    ],
  },

  // ─── C4: Fernanda Costa — Resolvido, onboarding concluído ───
  {
    id: 'conv4',
    contactId: 'ct4',
    contactName: 'Fernanda Costa',
    contactPhone: '+55 11 95678-2341',
    contactAvatar: av('Fernanda Costa', '7e22ce'),
    contactEmail: 'fernanda@costadvocacia.com.br',
    status: 'human',
    isActive: false,
    assignedTeam: null,
    assignedUserId: 'tm6',
    assignedUserName: 'Carla Dias',
    lastMessage: 'Muito obrigada pelo atendimento! Ficou ótimo.',
    lastMessageTime: 'Ontem',
    unreadCount: 0,
    primaryChannel: 'whatsapp',
    tags: ['Resolvido', 'Cliente VIP', 'Onboarding'],
    notes: 'Onboarding concluído. Tags configuradas: Consulta, Urgente, Cobrança, Trabalhista, Cível. Kickoff agendado para revisão de fluxos.',
    clientMemory: mem(
      'customer', 92,
      ['configuração assistida', 'tags automáticas', 'mensagem fora de horário'],
      [],
      ['Plano Profissional', 'Integração WhatsApp Business'],
      'educado e objetivo',
      ['dificuldade inicial de configuração', 'preocupação com automação no setor jurídico'],
      'Agendar revisão de fluxos em 30 dias após onboarding.',
      'R$ 200–400/mês',
      'Cliente ativo — iniciou onboarding',
      'Responde durante o horário comercial',
      'Configuração e onboarding da conta',
      1, 'manhã (9h–12h)'
    ),
    messages: [
      msg('c4m01', 'Bom dia! Fiz o cadastro mas não estou conseguindo configurar o QR Code do WhatsApp.', 9, 15, 'user'),
      msg('c4m02', 'Bom dia, Fernanda! Vou te ajudar a configurar. Você está na tela de "Integrações"?', 9, 16, 'nina'),
      msg('c4m03', 'Sim, estou aqui.', 9, 17, 'user'),
      msg('c4m04', 'Perfeito! Clique em "WhatsApp Business" e depois em "Conectar novo número".', 9, 18, 'nina'),
      msg('c4m05', 'Apareceu um QR Code mas meu celular não está lendo.', 9, 20, 'user'),
      msg('c4m06', 'Tente: WhatsApp Business → Dispositivos vinculados → Vincular dispositivo. Leia o QR Code com essa tela.', 9, 21, 'nina'),
      msg('c4m07', 'Funcionou! Apareceu "Conectado"! 🎉', 9, 23, 'user'),
      msg('c4m08', 'Ótimo! Agora vou te transferir para a Carla da nossa equipe de onboarding para finalizar as configurações.', 9, 24, 'nina'),
      msg('c4m09', 'Oi Fernanda! Aqui é a Carla. Vou te ajudar a configurar as mensagens de boas-vindas e o horário de atendimento. Tem uns 15 minutinhos?', 9, 25, 'human'),
      msg('c4m10', 'Tenho sim!', 9, 26, 'user'),
      msg('c4m11', 'Ótimo! Primeiro: qual o nome da sua empresa e o horário de atendimento?', 9, 27, 'human'),
      msg('c4m12', 'Fernanda Costa Advocacia. Atendemos de segunda a sexta das 8h às 18h.', 9, 28, 'user'),
      msg('c4m13', 'Configurado! Agora vamos definir a mensagem fora do horário. Que tal: "Obrigada pelo contato. Retornaremos no próximo dia útil."?', 9, 30, 'human'),
      msg('c4m14', 'Perfeito! Pode usar essa.', 9, 31, 'user'),
      msg('c4m15', 'Feito! Agora vou configurar as tags automáticas: "Consulta", "Urgente", "Cobrança". Faz sentido?', 9, 33, 'human'),
      msg('c4m16', 'Sim! Mas adiciona "Trabalhista" e "Cível" também.', 9, 35, 'user'),
      msg('c4m17', 'Adicionado! Sua configuração está completa. Quer que eu faça um teste?', 9, 36, 'human'),
      msg('c4m18', 'Sim, por favor!', 9, 37, 'user'),
      msg('c4m19', 'Enviei! Chegou pra você?', 9, 38, 'human'),
      msg('c4m20', 'Chegou! Ficou perfeito! ✅', 9, 39, 'user'),
      msg('c4m21', 'Sua conta está 100% configurada, Fernanda. Se precisar de qualquer ajuste, é só me chamar.', 9, 40, 'human'),
      msg('c4m22', 'Muito obrigada pelo atendimento! Ficou ótimo.', 9, 41, 'user'),
    ],
  },

  // ─── C5: Pedro Santos — VIP, SLA vencido, 5 não lidas ───
  {
    id: 'conv5',
    contactId: 'ct5',
    contactName: 'Pedro Santos',
    contactPhone: '+55 11 94523-8765',
    contactAvatar: av('Pedro Santos', 'b91c1c'),
    contactEmail: 'pedro@santospremium.com.br',
    status: 'human',
    isActive: true,
    assignedTeam: null,
    assignedUserId: 'tm4',
    assignedUserName: 'Patrícia Rocha',
    lastMessage: 'Vou cancelar meu contrato se não resolverem hoje!',
    lastMessageTime: '5min',
    unreadCount: 5,
    primaryChannel: 'whatsapp',
    tags: ['VIP', 'Cobrança', 'SLA Vencido', 'Urgente'],
    notes: 'URGENTE — Cliente VIP há 2 anos. Cobrado indevidamente. Estorno em atraso (8 dias úteis). Escalar para gerência imediatamente. Compensar com 1 mês gratuito já aprovado.',
    clientMemory: mem(
      'at-risk', 38,
      ['estabilidade financeira', 'transparência na cobrança', 'atendimento prioritário'],
      ['cobrança indevida não estornada', 'falta de comunicação proativa', 'suporte lento'],
      ['Plano Enterprise', 'Suporte VIP'],
      'exigente e formal',
      ['cobrança indevida há 8 dias úteis sem estorno', 'perda de confiança no suporte financeiro', 'ameaça de cancelamento'],
      'URGENTE: Escalar para gerência financeira agora. Garantir estorno TODAY e ligar pessoalmente para o cliente.',
      'Acima de R$ 1.200/mês',
      'Cliente em risco — decisão hoje',
      'Responde imediatamente quando insatisfeito',
      'Cobrança indevida e atraso no estorno',
      12, 'qualquer horário'
    ),
    messages: [
      msg('c5m01', 'Oi, minha fatura de junho está com cobrança errada.', 16, 0, 'user'),
      msg('c5m02', 'Olá, Pedro! Vou verificar sua fatura agora. Pode confirmar o CNPJ da empresa?', 16, 2, 'nina'),
      msg('c5m03', '12.345.678/0001-90', 16, 4, 'user'),
      msg('c5m04', 'Encontrei! Há um item adicional indevido na sua fatura. Vou acionar a equipe financeira.', 16, 5, 'nina'),
      msg('c5m05', 'Preciso que isso seja resolvido hoje. Sou cliente há 2 anos.', 16, 7, 'user'),
      msg('c5m06', 'Entendo a urgência. Transferindo para o Rodrigo do financeiro agora.', 16, 8, 'nina'),
      msg('c5m07', 'Oi Pedro! Aqui é o Rodrigo. Estou vendo sua fatura. O item adicional foi referente a um número extra adicionado em 3/06. Você autorizou?', 16, 9, 'human'),
      msg('c5m08', 'Não autorizei nada! Isso é uma cobrança indevida.', 16, 11, 'user'),
      msg('c5m09', 'Entendo. Vou estornar agora e investigar o ocorrido.', 16, 12, 'human'),
      msg('c5m10', 'Estorno solicitado. Em até 5 dias úteis o valor retorna no seu cartão. Peço desculpas pelo transtorno.', 16, 15, 'human'),
      msg('c5m11', 'Ok, obrigado. Mas quero garantia que não vai acontecer de novo.', 16, 17, 'user'),
      msg('c5m12', 'Com certeza. Vou bloquear a adição de novos números sem dupla confirmação. Mais alguma coisa?', 16, 18, 'human'),
      msg('c5m13', 'Por enquanto não. Mas fiquem atentos.', 16, 20, 'user'),
      msg('c5m14', 'O estorno não caiu ainda. Já se passaram mais de 5 dias úteis.', 10, 0, 'user'),
      msg('c5m15', 'Oi Pedro! Deixa eu verificar... Realmente o estorno ficou pendente por um erro interno. Me desculpe!', 10, 2, 'human'),
      msg('c5m16', 'Reprocessei manualmente. Deve cair em até 24h. Como compensação, vou adicionar 1 mês gratuito na sua próxima fatura.', 10, 5, 'human'),
      msg('c5m17', 'Isso é o mínimo! Que bagunça esse atendimento de vocês.', 10, 7, 'user'),
      msg('c5m18', 'O dinheiro ainda não voltou. Já são 8 dias úteis. Isso é inadmissível!', 9, 0, 'user', 'delivered'),
      msg('c5m19', 'Quero falar com o gerente agora.', 9, 2, 'user', 'delivered'),
      msg('c5m20', 'Ninguém me responde? Que absurdo!', 9, 5, 'user', 'delivered'),
      msg('c5m21', 'Isso é inadmissível! Precisamos resolver agora.', 9, 8, 'user', 'delivered'),
      msg('c5m22', 'Vou cancelar meu contrato se não resolverem hoje!', 9, 10, 'user', 'sent'),
    ],
  },

  // ─── C6: Clínica Vida Plena — Nina ativa, 1 não lida ───
  {
    id: 'conv6',
    contactId: 'ct6',
    contactName: 'Clínica Vida Plena',
    contactPhone: '+55 11 3456-7890',
    contactAvatar: av('Clinica Vida Plena', '065f46'),
    contactEmail: 'contato@vidaplena.med.br',
    status: 'nina',
    isActive: true,
    assignedTeam: null,
    assignedUserId: null,
    assignedUserName: null,
    lastMessage: 'Boa tarde! Gostaria de conhecer a plataforma para clínicas.',
    lastMessageTime: '15min',
    unreadCount: 1,
    primaryChannel: 'instagram',
    tags: ['Saúde', 'Demo Agendada', 'Empresa'],
    notes: null,
    clientMemory: mem(
      'prospect', 58,
      ['agendamento automático', 'redução de no-show', 'integração prontuário'],
      ['integração com planos de saúde ainda em beta'],
      ['Plano Saúde', 'módulo de agendamento'],
      'formal e técnico',
      ['alto volume de agendamentos manuais', 'taxa de no-show acima de 30%', 'recepção sobrecarregada'],
      'Preparar demo focada em agendamento automático e integração Tasy/MV Soul. Incluir dados de redução de no-show.',
      'R$ 700–1.000/mês',
      '7–15 dias',
      'Responde durante horário comercial',
      'Interesse em demo da plataforma para clínicas',
      1, 'tarde (14h–17h)'
    ),
    messages: [
      msg('c6m01', 'Boa tarde! Sou da Clínica Vida Plena. Gostaria de conhecer a plataforma para clínicas médicas.', 14, 15, 'user'),
      msg('c6m02', 'Boa tarde! É um prazer receber a Clínica Vida Plena 😊 Sou a Nina. Temos uma solução especializada para saúde. Me conta mais sobre a clínica!', 14, 15, 'nina'),
      msg('c6m03', 'Somos uma clínica multidisciplinar com 12 especialidades. Temos muita dificuldade em gerenciar agendamentos pelo WhatsApp.', 14, 17, 'user'),
      msg('c6m04', 'Entendo! Agendamento automático via WhatsApp com IA é exatamente nosso ponto forte para clínicas — agenda em tempo real verificando disponibilidade dos médicos.', 14, 18, 'nina'),
      msg('c6m05', 'Como funciona o agendamento automático?', 14, 20, 'user'),
      msg('c6m06', 'A IA integra com sua agenda (Google Calendar, Doctoralia, etc.) e agenda consultas automaticamente, confirmando por WhatsApp. Zero trabalho manual para a recepção.', 14, 21, 'nina'),
      msg('c6m07', 'Impressionante! Temos também problemas com não comparecimento. A IA manda lembrete automático?', 14, 23, 'user'),
      msg('c6m08', 'Sim! Enviamos lembretes 24h e 2h antes da consulta. Nossos clientes reduzem em média 35% o no-show. Quer ver ao vivo numa demo?', 14, 24, 'nina'),
      msg('c6m09', 'Com certeza! Quando têm disponibilidade?', 14, 25, 'user'),
      msg('c6m10', 'Tenho amanhã às 10h ou quinta-feira às 15h. Qual prefere?', 14, 26, 'nina'),
      msg('c6m11', 'Quinta às 15h. Quantas pessoas podem participar da demo?', 14, 27, 'user'),
      msg('c6m12', 'Quantas quiser! Clínicas costumam trazer gestor, recepcionista chefe e TI. A demo dura 45 minutos.', 14, 28, 'nina'),
      msg('c6m13', 'Perfeito! Vou confirmar a participação da nossa equipe.', 14, 29, 'user'),
      msg('c6m14', 'Ótimo! Agendado para quinta às 15h 📅 Enviarei o link da reunião por aqui. Tem mais alguma dúvida?', 14, 30, 'nina'),
      msg('c6m15', 'Tem integração com prontuário eletrônico?', 14, 31, 'user'),
      msg('c6m16', 'Sim! Integramos com Tasy, MV Soul, Pixeon e outros. Quer que inclua na demonstração?', 14, 32, 'nina'),
      msg('c6m17', 'Sim! E integra com planos de saúde para autorização prévia?', 14, 33, 'user'),
      msg('c6m18', 'Essa funcionalidade está em beta. Vou incluir na demo para mostrar o que já está disponível.', 14, 34, 'nina'),
      msg('c6m19', 'Boa tarde! Gostaria de conhecer a plataforma para clínicas.', 14, 35, 'user', 'sent'),
    ],
  },

  // ─── C7: Lumina Iluminação — Paused, aguardando equipe, 2 dias ───
  {
    id: 'conv7',
    contactId: 'ct7',
    contactName: 'Lumina Iluminação',
    contactPhone: '+55 11 3234-5678',
    contactAvatar: av('Lumina Iluminacao', 'b45309'),
    contactEmail: 'comercial@luminailuminacao.com.br',
    status: 'paused',
    isActive: true,
    assignedTeam: null,
    assignedUserId: 'tm5',
    assignedUserName: 'Felipe Mendonça',
    lastMessage: 'A proposta foi enviada para nossa diretoria. Aguardando aprovação.',
    lastMessageTime: '2d',
    unreadCount: 0,
    primaryChannel: 'facebook',
    tags: ['Proposta', 'Empresa', 'Aguardando Equipe'],
    notes: 'Contrato pode ser em nome da holding (não da Lumina diretamente). SLA 99,9% já nos termos. Relatório por departamento sem custo extra. Reunião de fechamento agendada para daqui a 7 dias.',
    clientMemory: mem(
      'negotiation', 78,
      ['integração SAP B1', 'SLA garantido', 'treinamento incluído', 'relatório por departamento'],
      ['operação 24/7 exige suporte robusto', 'contrato deve ser na holding'],
      ['Plano Corporativo', 'integração SAP B1'],
      'técnico e corporativo',
      ['ausência de integração SAP', 'suporte 24/7 limitado', 'falta de visibilidade por departamento'],
      'Aguardar decisão da diretoria. Follow-up em 3 dias se não houver retorno.',
      'Acima de R$ 2.000/mês',
      '5–10 dias — decisão da diretoria',
      'Responde dentro do dia útil',
      'Análise de proposta e ajustes para aprovação da diretoria',
      3, 'manhã (9h–11h)'
    ),
    messages: [
      msg('c7m01', 'Bom dia! Recebi a proposta comercial da Integra Connect. Posso tirar umas dúvidas?', 9, 0, 'user'),
      msg('c7m02', 'Bom dia! Claro, pode perguntar. Aqui é o Felipe, executivo de contas.', 9, 1, 'human'),
      msg('c7m03', 'A proposta fala em "API proprietária". Nosso TI perguntou se consegue integrar com nosso ERP SAP B1.', 9, 3, 'user'),
      msg('c7m04', 'Sim! Temos conector nativo para SAP Business One. Vou te enviar a documentação técnica.', 9, 4, 'human'),
      msg('c7m05', 'Ótimo! O plano inclui treinamento da equipe?', 9, 6, 'user'),
      msg('c7m06', 'O Plano Corporativo inclui 8 horas de treinamento presencial ou remoto, agendado junto com o onboarding.', 9, 7, 'human'),
      msg('c7m07', 'Perfeito! E o SLA de suporte? Nosso e-commerce funciona 24/7.', 9, 9, 'user'),
      msg('c7m08', 'Para o Plano Corporativo: SLA de 2h no horário comercial e 4h fora dele. Monitoramento 24/7 para incidentes críticos.', 9, 10, 'human'),
      msg('c7m09', 'Isso é suficiente. Mais uma coisa: o contrato pode ser em nome da holding e não da Lumina diretamente?', 9, 12, 'user'),
      msg('c7m10', 'Sim! Sem problema. Basta informar o CNPJ da holding que emitimos o contrato assim.', 9, 13, 'human'),
      msg('c7m11', 'Vou passar tudo isso para a diretoria. Eles se reúnem amanhã.', 9, 15, 'user'),
      msg('c7m12', 'Perfeito! Se precisar de mais informação para a reunião, pode me chamar. Boa sorte!', 9, 16, 'human'),
      msg('c7m13', 'Obrigado, Felipe! Até mais.', 9, 17, 'user'),
      msg('c7m14', 'Oi Felipe! A diretoria viu a proposta mas pediu dois ajustes antes de assinar.', 14, 30, 'user'),
      msg('c7m15', 'Oi! Pode falar, quais são os ajustes?', 14, 31, 'human'),
      msg('c7m16', 'Primeiro: eles querem garantia de uptime de 99,9%. Segundo: precisam de relatório mensal de uso por departamento.', 14, 32, 'user'),
      msg('c7m17', 'Perfeito! O SLA de 99,9% já está em nossos termos (posso enviar o documento). E o relatório por departamento pode ser customizado sem custo adicional.', 14, 34, 'human'),
      msg('c7m18', 'Eles vão adorar! Vou confirmar com eles ainda hoje.', 14, 36, 'user'),
      msg('c7m19', 'Aguardo! Qualquer dúvida pode me chamar.', 14, 37, 'human'),
      msg('c7m20', 'A proposta foi enviada para nossa diretoria. Aguardando aprovação.', 14, 38, 'user'),
    ],
  },

  // ─── C8: Ricardo Almeida — Tentativa de cancelamento, retenção ───
  {
    id: 'conv8',
    contactId: 'ct8',
    contactName: 'Ricardo Almeida',
    contactPhone: '+55 11 93456-7890',
    contactAvatar: av('Ricardo Almeida', '6d28d9'),
    contactEmail: 'ricardo.almeida@consultoria.com',
    status: 'human',
    isActive: true,
    assignedTeam: null,
    assignedUserId: 'tm4',
    assignedUserName: 'Patrícia Rocha',
    lastMessage: 'Você ainda está aí?',
    lastMessageTime: '35min',
    unreadCount: 2,
    primaryChannel: 'whatsapp',
    tags: ['Cancelamento', 'Retenção', 'Urgente'],
    notes: 'Atendimento iniciado pela IA. Problema real: erro de calibração de prompts da semana passada (já corrigido em 30/06). Compensação aprovada: 2 meses grátis + consultoria 2h. Prazo de 15 dias para provar melhoria.',
    clientMemory: mem(
      'at-risk', 32,
      ['confiabilidade da IA', 'qualidade das respostas automáticas'],
      ['erros de IA causaram prejuízo real', 'falta de notificação proativa sobre problemas'],
      ['Plano Profissional'],
      'direto e impaciente',
      ['erros de IA em respostas para clientes', 'perda de clientes por falha do sistema', 'falta de comunicação sobre incidentes'],
      'Monitoramento diário pessoal da Patrícia. Enviar relatório de qualidade semanal. Verificar se não houve mais erros antes de responder.',
      'R$ 300–500/mês',
      '15 dias de prazo — decisão de cancelamento',
      'Responde rapidamente quando insatisfeito',
      'Solicitação de cancelamento por erros de IA',
      3, 'manhã (8h–10h)'
    ),
    messages: [
      msg('c8m01', 'Quero cancelar meu plano. Não estou satisfeito com o serviço.', 8, 30, 'user'),
      msg('c8m02', 'Olá, Ricardo! Que pena em ouvir isso. Pode me contar o que aconteceu? Quero entender para te ajudar.', 8, 31, 'nina'),
      msg('c8m03', 'Já faz 3 semanas que a IA está cometendo erros. Ela prometeu desconto que não existe e agendou reuniões no horário errado.', 8, 33, 'user'),
      msg('c8m04', 'Entendo sua frustração, Ricardo. Esses erros são inaceitáveis. Vou te conectar imediatamente com nossa equipe de sucesso do cliente.', 8, 34, 'nina'),
      msg('c8m05', 'Oi Ricardo! Aqui é a Patrícia, gerente de sucesso do cliente. Acabei de ver o relato e quero resolver isso hoje.', 8, 35, 'human'),
      msg('c8m06', 'Oi Patrícia. Já perdi dois clientes por causa dessas respostas erradas. Isso me causou prejuízo real.', 8, 37, 'user'),
      msg('c8m07', 'Entendo completamente. Isso é sério e você tem razão. Já estou puxando o histórico das conversas para ver o que aconteceu.', 8, 38, 'human'),
      msg('c8m08', 'Encontrei. Houve um problema de calibração nos prompts de IA após uma atualização na semana passada. Já corrigimos ontem.', 8, 40, 'human'),
      msg('c8m09', 'Por que ninguém me avisou?', 8, 42, 'user'),
      msg('c8m10', 'Foi um erro nosso de comunicação. Devíamos ter te notificado proativamente. Me desculpe.', 8, 43, 'human'),
      msg('c8m11', 'E meus clientes que foram prejudicados?', 8, 45, 'user'),
      msg('c8m12', 'Posso te oferecer: 2 meses de serviço gratuito como compensação + consultoria de 2h para revisar todos os seus fluxos de atendimento.', 8, 46, 'human'),
      msg('c8m13', 'Isso compensa um pouco, mas ainda estou considerando cancelar.', 8, 48, 'user'),
      msg('c8m14', 'Compreendo. Mas antes de decidir, posso te pedir 15 dias para demonstrar a melhoria? Os erros foram corrigidos e você tem minha palavra pessoal.', 8, 49, 'human'),
      msg('c8m15', '15 dias. Se houver mais um erro, cancelo sem discussão.', 8, 51, 'user'),
      msg('c8m16', 'Trato feito. Vou te adicionar no meu acompanhamento diário pessoal. Você vai sentir a diferença.', 8, 52, 'human'),
      msg('c8m17', 'Espero que sim.', 8, 54, 'user'),
      msg('c8m18', 'Já configurei o monitoramento. Tem mais uma solicitação: pode me mandar o nome dos clientes afetados? Quero que enviemos uma nota de retificação.', 8, 56, 'human'),
      msg('c8m19', 'Vou verificar e te mando.', 8, 58, 'user'),
      msg('c8m20', 'Quero cancelar meu plano, não estou satisfeito.', 9, 5, 'user', 'delivered'),
      msg('c8m21', 'Você ainda está aí?', 9, 8, 'user', 'sent'),
    ],
  },

  // ─── C9: Ana Souza — IA prospectando, lead frio ───
  {
    id: 'conv9',
    contactId: 'ct9',
    contactName: 'Ana Souza',
    contactPhone: '+55 11 92345-6789',
    contactAvatar: av('Ana Souza', '0f766e'),
    contactEmail: 'ana.souza@minhaloja.com.br',
    status: 'nina',
    isActive: true,
    assignedTeam: null,
    assignedUserId: null,
    assignedUserName: null,
    lastMessage: 'Interessante! Me manda mais informações por favor.',
    lastMessageTime: '1h',
    unreadCount: 0,
    primaryChannel: 'telegram',
    tags: ['Lead', 'E-commerce', 'Prospecto'],
    notes: null,
    clientMemory: mem(
      'prospect', 44,
      ['automação de respostas repetitivas', 'tranquilidade no Black Friday'],
      ['preço pode ser alto para uma loja pequena'],
      ['Plano Starter'],
      'informal e curiosa',
      ['sobrecarregada de mensagens', 'responde sozinha até de madrugada', 'loja sem equipe de suporte'],
      'Enviar proposta personalizada para Plano Starter com foco em e-commerce. Destacar Black Friday como case de uso.',
      'R$ 150–250/mês',
      '2–4 semanas',
      'Responde rápido e informalmente',
      'Interesse em automação de atendimento para loja virtual',
      1, 'tarde e noite'
    ),
    messages: [
      msg('c9m01', 'Oi! Vi um anúncio de vocês e fiquei curiosa.', 8, 0, 'user'),
      msg('c9m02', 'Oi, Ana! Que bom ter você aqui 😊 Sou a Nina. O que te chamou a atenção no anúncio?', 8, 1, 'nina'),
      msg('c9m03', 'Falava sobre atendimento automático pelo WhatsApp. Tenho uma loja virtual e fico sobrecarregada de mensagens.', 8, 2, 'user'),
      msg('c9m04', 'Entendo muito bem! Nosso sistema deixa a IA cuidar das perguntas repetitivas — status do pedido, prazo de entrega, estoque — e você foca no que realmente importa.', 8, 3, 'nina'),
      msg('c9m05', 'Quantas mensagens por dia vocês conseguem gerenciar?', 8, 4, 'user'),
      msg('c9m06', 'Sem limite! Trabalhamos com picos de milhares de mensagens simultâneas. Perfeito para datas como Black Friday.', 8, 5, 'nina'),
      msg('c9m07', 'Black Friday é meu pesadelo! Fico acordada até de madrugada respondendo.', 8, 7, 'user'),
      msg('c9m08', 'Imagino! Com a Integra, você dorme tranquila — a IA atende no seu lugar com as suas respostas personalizadas 😴', 8, 8, 'nina'),
      msg('c9m09', 'Mas será que a IA consegue responder sobre meus produtos específicos?', 8, 9, 'user'),
      msg('c9m10', 'Sim! Você cadastra o catálogo com fotos, descrições e respostas personalizadas. A IA aprende e responde como se fosse você.', 8, 10, 'nina'),
      msg('c9m11', 'E se o cliente precisar de um humano?', 8, 12, 'user'),
      msg('c9m12', 'A IA detecta quando o cliente precisa de atendimento humano e te notifica. Você assume com um clique.', 8, 13, 'nina'),
      msg('c9m13', 'Que bacana! Quanto custa?', 8, 15, 'user'),
      msg('c9m14', 'Temos planos a partir de R$ 197/mês para lojas com até 2 atendentes. Quer receber uma proposta personalizada por email?', 8, 16, 'nina'),
      msg('c9m15', 'Sim! Meu email é ana.souza@minhaloja.com.br', 8, 17, 'user'),
      msg('c9m16', 'Anotado! Vou preparar uma proposta e te enviar até amanhã. Mais alguma dúvida?', 8, 18, 'nina'),
      msg('c9m17', 'Interessante! Me manda mais informações por favor.', 8, 19, 'user'),
    ],
  },

  // ─── C10: Juliana Martins — Negociação acirrada, 4 não lidas ───
  {
    id: 'conv10',
    contactId: 'ct10',
    contactName: 'Juliana Martins',
    contactPhone: '+55 11 91234-5678',
    contactAvatar: av('Juliana Martins', '9f1239'),
    contactEmail: 'juliana@farmaciasunidas.com.br',
    status: 'human',
    isActive: true,
    assignedTeam: null,
    assignedUserId: 'tm5',
    assignedUserName: 'Felipe Mendonça',
    lastMessage: 'Consigo fechar se vier com 15% de desconto no anual.',
    lastMessageTime: '12min',
    unreadCount: 4,
    primaryChannel: 'webchat',
    tags: ['Negociação', 'Hot Lead', 'Indicação', 'Enterprise'],
    notes: 'Indicação do Carlos Mendes. 8 farmácias com IA customizada por filial. Orçamento da diretoria: R$ 2.800/mês. Proposta atual: R$ 3.200 (com suporte 24/7). Sem suporte 24h: R$ 3.000. Com 15% de desconto no anual: R$ 2.720/mês. Precisar de aprovação da Sarah para fechar abaixo de R$ 3.000.',
    clientMemory: mem(
      'hot-prospect', 87,
      ['IA por filial', 'relatório consolidado de rede', 'escalabilidade'],
      ['preço acima do orçamento aprovado', 'precisam de aprovação da diretoria hoje'],
      ['Plano Multi-Unidade', 'IA customizada por filial'],
      'negociador experiente, decisivo',
      ['gerenciar 8 filiais com IA diferente por especialidade', 'visibilidade consolidada da rede', 'falta de personalização por filial em soluções concorrentes'],
      'URGENTE: Obter aprovação da Sarah para 15% de desconto no anual (R$ 2.720/mês). Responder antes das 17h — prazo da diretoria.',
      'R$ 2.800/mês (aprovado pela diretoria)',
      'Hoje — prazo da diretoria expira hoje',
      'Decisiva, responde imediatamente',
      'Negociação de proposta customizada para rede de 8 farmácias',
      1, 'manhã e tarde'
    ),
    messages: [
      msg('c10m01', 'Bom dia! Fui indicada pelo Carlos Mendes. Ele falou muito bem de vocês.', 7, 0, 'user'),
      msg('c10m02', 'Bom dia, Juliana! Que honra receber uma indicação do Carlos! Aqui é o Felipe. Como posso te ajudar?', 7, 1, 'human'),
      msg('c10m03', 'Preciso de uma solução completa para minha rede de farmácias. São 8 unidades com atendimento via WhatsApp.', 7, 2, 'user'),
      msg('c10m04', 'Perfeito! Para redes multi-unidade temos uma solução especialmente desenvolvida. Quer que eu monte uma proposta customizada?', 7, 3, 'human'),
      msg('c10m05', 'Sim! Mas primeiro: dá para separar as conversas por filial?', 7, 4, 'user'),
      msg('c10m06', 'Sim! Cada filial tem seu próprio número e inbox, mas você tem visão consolidada de toda a rede em um único painel.', 7, 5, 'human'),
      msg('c10m07', 'E relatório de performance por filial?', 7, 7, 'user'),
      msg('c10m08', 'Completo! Tempo médio de atendimento, satisfação do cliente, volume de mensagens — tudo por filial e consolidado.', 7, 8, 'human'),
      msg('c10m09', 'Ótimo! E a IA pode ser diferente em cada filial? Por exemplo, uma especializada em manipulação e outra em perfumaria?', 7, 9, 'user'),
      msg('c10m10', 'Exatamente! Cada filial tem seu próprio perfil de IA com produtos e respostas específicos.', 7, 10, 'human'),
      msg('c10m11', 'Me impressionou! Manda a proposta.', 7, 12, 'user'),
      msg('c10m12', 'Vou preparar uma proposta para 8 unidades com IA customizada por filial. Te envio até o final do dia.', 7, 14, 'human'),
      msg('c10m13', 'Combinado!', 7, 15, 'user'),
      msg('c10m14', 'Juliana, proposta enviada por email! Ficou em 3 páginas com todos os detalhes.', 9, 30, 'human'),
      msg('c10m15', 'Recebi! Estou lendo... Ficou bem completa. Mas o valor está um pouco acima do que esperávamos.', 9, 31, 'user'),
      msg('c10m16', 'Entendo! Posso te explicar o que está incluído para vermos onde podemos ajustar?', 9, 33, 'human'),
      msg('c10m17', 'Claro. O que pesa mais no preço?', 9, 34, 'user'),
      msg('c10m18', 'O maior custo é a customização de IA por filial (8 perfis individuais) + suporte prioritário 24/7. O resto é escalável.', 9, 35, 'human'),
      msg('c10m19', 'O suporte 24/7 não precisa ser 24h. Com 18h atendemos bem.', 9, 37, 'user'),
      msg('c10m20', 'Nesse caso, consigo reduzir R$ 200/mês no total. Fica melhor?', 9, 38, 'human'),
      msg('c10m21', 'Melhora! Mas ainda preciso de mais desconto. O orçamento aprovado pela diretoria é de R$ 2.800/mês.', 9, 40, 'user'),
      msg('c10m22', 'A proposta está em R$ 3.200. Preciso de autorização interna para ir abaixo de R$ 3.000.', 9, 41, 'human'),
      msg('c10m23', 'Consigo fechar agora se vier com 15% de desconto no anual.', 9, 43, 'user', 'delivered'),
      msg('c10m24', 'Minha diretoria só aprova até hoje.', 9, 45, 'user', 'delivered'),
      msg('c10m25', 'Felipe, estamos aguardando.', 9, 47, 'user', 'delivered'),
      msg('c10m26', 'Consigo fechar se vier com 15% de desconto no anual.', 9, 50, 'user', 'sent'),
    ],
  },
];

// ──────────────────────────────────────────────
// CRM — PESSOAS (Sprint 007)
// ──────────────────────────────────────────────

export const MOCK_PEOPLE: Person[] = [
  {
    id: 'ct1',
    name: 'João Silva',
    company: 'Contabilidade João Silva',
    companyId: 'comp1',
    document: '123.456.789-00',
    email: 'joao.silva@contabilidade.com.br',
    phones: ['+55 11 98432-1567'],
    whatsapp: '+55 11 98432-1567',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    origin: 'Instagram',
    tags: ['Novo Lead', 'Contabilidade', 'Demo Agendada'],
    notes: 'Cliente prefere contato pela manhã. Demo agendada para amanhã às 14h. Integração com ContaAzul é pré-requisito.',
    status: 'lead',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-01T09:30:00.000Z',
    // Sprint 008 — unified history example: same customer, three messaging
    // channels linked to this single Person, never duplicated.
    channelIdentities: [
      { channel: 'whatsapp', externalId: '+5511984321567', externalLabel: '+55 11 98432-1567', linkedAt: '2026-06-01T08:00:00.000Z' },
      { channel: 'instagram', externalId: 'joao.silva.ig', externalLabel: '@joao.silva.ig', linkedAt: '2026-06-20T14:00:00.000Z' },
      { channel: 'webchat', externalId: 'webchat-session-ct1', linkedAt: '2026-07-01T09:00:00.000Z' },
    ],
  },
  {
    id: 'ct2',
    name: 'Maria Oliveira',
    company: 'Oliveira Corp',
    companyId: 'comp2',
    document: '987.654.321-00',
    email: 'maria@oliveiracorp.com.br',
    phones: ['+55 11 97654-3210'],
    whatsapp: '+55 11 97654-3210',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    origin: 'Indicação',
    tags: ['Cliente', 'Renovação', 'VIP'],
    notes: 'Configurar renovação automática de token de WhatsApp Business a cada 90 dias.',
    status: 'customer',
    createdAt: '2025-03-15T08:00:00.000Z',
    updatedAt: '2026-07-01T08:45:00.000Z',
  },
  {
    id: 'ct3',
    name: 'Carlos Mendes',
    company: 'Construtora Mendes',
    companyId: 'comp3',
    document: '12.345.678/0001-90',
    email: 'carlosmendes@construtora.com.br',
    phones: ['+55 11 96789-4532', '+55 11 3123-4567'],
    whatsapp: '+55 11 96789-4532',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    origin: 'Google Ads',
    tags: ['Enterprise', 'Hot Lead', 'Negociação'],
    notes: 'Sempre solicitar aprovação interna antes de gerar contrato. Reunião de fechamento agendada para quinta.',
    status: 'lead',
    createdAt: '2026-05-10T08:00:00.000Z',
    updatedAt: '2026-07-01T07:55:00.000Z',
  },
  {
    id: 'ct4',
    name: 'Fernanda Costa',
    company: 'Fernanda Costa Advocacia',
    companyId: 'comp4',
    document: '456.789.012-00',
    email: 'fernanda@costadvocacia.com.br',
    phones: ['+55 11 95678-2341'],
    whatsapp: '+55 11 95678-2341',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm6',
    ownerName: 'Carla Dias',
    origin: 'LinkedIn',
    tags: ['Jurídico', 'Onboarding', 'Cliente VIP'],
    notes: 'Onboarding concluído. Tags configuradas. Kickoff agendado para revisão de fluxos.',
    status: 'customer',
    createdAt: '2026-04-20T08:00:00.000Z',
    updatedAt: '2026-06-30T09:41:00.000Z',
  },
  {
    id: 'ct5',
    name: 'Pedro Santos',
    company: 'Santos Premium Group',
    companyId: 'comp5',
    document: '789.012.345-00',
    email: 'pedro@santospremium.com.br',
    phones: ['+55 11 94523-8765'],
    whatsapp: '+55 11 94523-8765',
    city: 'Campinas',
    state: 'SP',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    origin: 'Indicação',
    tags: ['VIP', 'Em Risco', 'SLA Vencido'],
    notes: 'URGENTE — Cliente VIP há 2 anos. Cobrado indevidamente. Escalar para gerência imediatamente.',
    status: 'customer',
    createdAt: '2024-06-01T08:00:00.000Z',
    updatedAt: '2026-07-01T09:10:00.000Z',
  },
  {
    id: 'ct8',
    name: 'Ricardo Almeida',
    company: 'Ricardo Almeida Consultoria',
    companyId: 'comp6',
    document: '321.654.987-00',
    email: 'ricardo.almeida@consultoria.com',
    phones: ['+55 11 93456-7890'],
    whatsapp: '+55 11 93456-7890',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    origin: 'Referência',
    tags: ['Cancelamento', 'Retenção', 'Urgente'],
    notes: 'Compensação aprovada: 2 meses grátis + consultoria 2h. Prazo de 15 dias para provar melhoria.',
    status: 'customer',
    createdAt: '2025-01-10T08:00:00.000Z',
    updatedAt: '2026-07-01T08:58:00.000Z',
  },
  {
    id: 'ct9',
    name: 'Ana Souza',
    email: 'ana.souza@minhaloja.com.br',
    phones: ['+55 11 92345-6789'],
    whatsapp: '+55 11 92345-6789',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    origin: 'Instagram Ads',
    tags: ['Lead', 'E-commerce', 'Prospecto'],
    status: 'lead',
    createdAt: '2026-06-28T08:00:00.000Z',
    updatedAt: '2026-07-01T08:19:00.000Z',
  },
  {
    id: 'ct10',
    name: 'Juliana Martins',
    company: 'Farmácias Unidas Martins',
    companyId: 'comp7',
    document: '98.765.432/0001-10',
    email: 'juliana@farmaciasunidas.com.br',
    phones: ['+55 11 91234-5678', '+55 11 3456-0000'],
    whatsapp: '+55 11 91234-5678',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    origin: 'Indicação — Carlos Mendes',
    tags: ['Negociação', 'Hot Lead', 'Enterprise'],
    notes: 'Indicação do Carlos Mendes. 8 farmácias com IA customizada por filial. Orçamento da diretoria: R$ 2.800/mês.',
    status: 'lead',
    createdAt: '2026-06-25T08:00:00.000Z',
    updatedAt: '2026-07-01T09:50:00.000Z',
  },
];

// ──────────────────────────────────────────────
// CRM — EMPRESAS (Sprint 007)
// ──────────────────────────────────────────────

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp1',
    razaoSocial: 'João Silva Contabilidade ME',
    nomeFantasia: 'Contabilidade João Silva',
    cnpj: '12.345.678/0001-00',
    segmento: 'Contabilidade',
    porte: 'pequena',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.contabilidadejoaosilva.com.br',
    notes: 'Escritório de contabilidade com foco em PMEs. 3 atendentes.',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-01T09:30:00.000Z',
    contactIds: ['ct1'],
    dealIds: ['dl1'],
  },
  {
    id: 'comp2',
    razaoSocial: 'Oliveira Corp Ltda',
    nomeFantasia: 'Oliveira Corp',
    cnpj: '98.765.432/0001-00',
    segmento: 'Tecnologia',
    porte: 'media',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    website: 'www.oliveiracorp.com.br',
    notes: 'Cliente ativo. Renovação do contrato em outubro.',
    createdAt: '2025-03-15T08:00:00.000Z',
    updatedAt: '2026-07-01T08:45:00.000Z',
    contactIds: ['ct2'],
    dealIds: ['dl2'],
  },
  {
    id: 'comp3',
    razaoSocial: 'Construtora Mendes S.A.',
    nomeFantasia: 'Construtora Mendes',
    cnpj: '45.678.901/0001-00',
    segmento: 'Construção Civil',
    porte: 'grande',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.construtoraemendes.com.br',
    notes: 'Empresa com múltiplas unidades. Decisão corporativa.',
    createdAt: '2026-05-10T08:00:00.000Z',
    updatedAt: '2026-07-01T07:55:00.000Z',
    contactIds: ['ct3'],
    dealIds: ['dl3'],
  },
  {
    id: 'comp4',
    razaoSocial: 'Fernanda Costa Advocacia e Consultoria',
    nomeFantasia: 'Costa Advocacia',
    cnpj: '56.789.012/0001-00',
    segmento: 'Jurídico',
    porte: 'pequena',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm6',
    ownerName: 'Carla Dias',
    website: 'www.costadvocacia.com.br',
    createdAt: '2026-04-20T08:00:00.000Z',
    updatedAt: '2026-06-30T09:41:00.000Z',
    contactIds: ['ct4'],
    dealIds: ['dl4'],
  },
  {
    id: 'comp5',
    razaoSocial: 'Santos Premium Group Ltda',
    nomeFantasia: 'Santos Premium',
    cnpj: '67.890.123/0001-00',
    segmento: 'Comércio',
    porte: 'grande',
    city: 'Campinas',
    state: 'SP',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    website: 'www.santospremiumgroup.com.br',
    notes: 'Cliente VIP há 2 anos. Conta estratégica.',
    createdAt: '2024-06-01T08:00:00.000Z',
    updatedAt: '2026-07-01T09:10:00.000Z',
    contactIds: ['ct5'],
    dealIds: ['dl5'],
  },
  {
    id: 'comp6',
    razaoSocial: 'Ricardo Almeida Consultoria e Gestão ME',
    nomeFantasia: 'Almeida Consultoria',
    cnpj: '78.901.234/0001-00',
    segmento: 'Consultoria',
    porte: 'pequena',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    createdAt: '2025-01-10T08:00:00.000Z',
    updatedAt: '2026-07-01T08:58:00.000Z',
    contactIds: ['ct8'],
    dealIds: ['dl8'],
  },
  {
    id: 'comp7',
    razaoSocial: 'Farmácias Unidas Martins S.A.',
    nomeFantasia: 'Farmácias Unidas',
    cnpj: '89.012.345/0001-00',
    segmento: 'Farmácia / Saúde',
    porte: 'grande',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.farmaciasunidas.com.br',
    notes: '8 unidades. IA customizada por filial. Indicação do Carlos Mendes.',
    createdAt: '2026-06-25T08:00:00.000Z',
    updatedAt: '2026-07-01T09:50:00.000Z',
    contactIds: ['ct10'],
    dealIds: ['dl10'],
  },
  {
    id: 'comp8',
    razaoSocial: 'Clínica Vida Plena Serviços Médicos Ltda',
    nomeFantasia: 'Clínica Vida Plena',
    cnpj: '90.123.456/0001-00',
    segmento: 'Saúde',
    porte: 'media',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.clinicavidaplena.med.br',
    notes: '12 especialidades. Alto volume de agendamentos manuais.',
    createdAt: '2026-06-15T08:00:00.000Z',
    updatedAt: '2026-07-01T14:35:00.000Z',
    contactIds: ['ct6'],
    dealIds: ['dl6'],
  },
  {
    id: 'comp9',
    razaoSocial: 'Lumina Iluminação Comércio e Industria Ltda',
    nomeFantasia: 'Lumina Iluminação',
    cnpj: '01.234.567/0001-00',
    segmento: 'Indústria / Comércio',
    porte: 'grande',
    city: 'Guarulhos',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.luminailuminacao.com.br',
    notes: 'Operação 24/7. Contrato pode ser em nome da holding. SLA 99,9% já nos termos.',
    createdAt: '2026-05-20T08:00:00.000Z',
    updatedAt: '2026-06-29T14:38:00.000Z',
    contactIds: ['ct7'],
    dealIds: ['dl7'],
  },
];

// ──────────────────────────────────────────────
// CRM — TAREFAS (Sprint 007)
// ──────────────────────────────────────────────

const todayISO = new Date().toISOString();
const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

export const MOCK_TASKS: Task[] = [
  {
    id: 'task1',
    title: 'Confirmar participação na demo amanhã às 14h',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(0),
    priority: 'high',
    status: 'pending',
    origin: 'conversation',
    originId: 'conv1',
    personId: 'ct1',
    personName: 'João Silva',
    dealId: 'dl1',
    dealTitle: 'Automação de Atendimento',
    companyId: 'comp1',
    companyName: 'Contabilidade João Silva',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task2',
    title: 'Enviar proposta revisada com SLA 99,9%',
    description: 'Incluir relatório por departamento sem custo extra e cláusula de holding.',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(1),
    priority: 'high',
    status: 'pending',
    origin: 'deal',
    originId: 'dl7',
    personId: 'ct7',
    personName: 'Lumina Iluminação',
    dealId: 'dl7',
    dealTitle: 'Integração SAP + WhatsApp',
    companyId: 'comp9',
    companyName: 'Lumina Iluminação',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task3',
    title: 'Obter aprovação da Sarah para 15% de desconto',
    description: 'Farmácias Unidas — orçamento aprovado R$ 2.800/mês. Proposta atual R$ 3.200.',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(0),
    priority: 'high',
    status: 'in_progress',
    origin: 'deal',
    originId: 'dl10',
    personId: 'ct10',
    personName: 'Juliana Martins',
    dealId: 'dl10',
    dealTitle: 'Plano Multi-Unidade — 8 Farmácias',
    companyId: 'comp7',
    companyName: 'Farmácias Unidas',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task4',
    title: 'Escalar estorno de Pedro Santos para gerência financeira',
    description: 'Estorno em atraso (8 dias úteis). Compensação: 1 mês gratuito já aprovado.',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    dueDate: daysFromNow(0),
    priority: 'high',
    status: 'pending',
    origin: 'conversation',
    originId: 'conv5',
    personId: 'ct5',
    personName: 'Pedro Santos',
    dealId: 'dl5',
    dealTitle: 'Renovação Contrato VIP',
    companyId: 'comp5',
    companyName: 'Santos Premium Group',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task5',
    title: 'Follow-up Carlos Mendes — reunião de fechamento quinta 15h',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(3),
    priority: 'medium',
    status: 'pending',
    origin: 'deal',
    originId: 'dl3',
    personId: 'ct3',
    personName: 'Carlos Mendes',
    dealId: 'dl3',
    dealTitle: 'Plano Corporativo Business',
    companyId: 'comp3',
    companyName: 'Construtora Mendes',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task6',
    title: 'Preparar demo clínica — agendamento automático + integração Tasy/MV Soul',
    description: 'Incluir dados de redução de no-show. Demo quinta às 15h.',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(2),
    priority: 'medium',
    status: 'in_progress',
    origin: 'deal',
    originId: 'dl6',
    personId: 'ct6',
    personName: 'Clínica Vida Plena',
    dealId: 'dl6',
    dealTitle: 'Plano Saúde — Clínica Multidisciplinar',
    companyId: 'comp8',
    companyName: 'Clínica Vida Plena',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task7',
    title: 'Enviar proposta Plano Starter para Ana Souza',
    description: 'Foco em e-commerce. Destacar Black Friday como case de uso.',
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    dueDate: daysFromNow(1),
    priority: 'low',
    status: 'pending',
    origin: 'conversation',
    originId: 'conv9',
    personId: 'ct9',
    personName: 'Ana Souza',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task8',
    title: 'Monitoramento diário Ricardo Almeida — verificar qualidade IA',
    description: 'Prazo: 15 dias. Enviar relatório de qualidade semanal.',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    dueDate: daysFromNow(15),
    priority: 'medium',
    status: 'in_progress',
    origin: 'person',
    originId: 'ct8',
    personId: 'ct8',
    personName: 'Ricardo Almeida',
    dealId: 'dl8',
    dealTitle: 'Contrato de Retenção',
    companyId: 'comp6',
    companyName: 'Almeida Consultoria',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
];

// ──────────────────────────────────────────────
// CRM — TIMELINE (Sprint 007)
// ──────────────────────────────────────────────

export const MOCK_TIMELINE_ENTRIES: TimelineEntry[] = [
  {
    id: 'tl1',
    type: 'stage_change',
    content: 'Negócio movido para Qualificação',
    metadata: { from: 'Novo Lead', to: 'Qualificação', dealTitle: 'Automação de Atendimento' },
    personId: 'ct1',
    dealId: 'dl1',
    conversationId: 'conv1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-07-01T09:15:00.000Z',
    source: 'human',
  },
  {
    id: 'tl2',
    type: 'task',
    content: 'Tarefa criada: Confirmar participação na demo às 14h',
    metadata: { taskId: 'task1', priority: 'high' },
    personId: 'ct1',
    dealId: 'dl1',
    taskId: 'task1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-07-01T09:00:00.000Z',
    source: 'human',
  },
  {
    id: 'tl3',
    type: 'ai_action',
    content: 'Nina qualificou o lead: score 65/100',
    metadata: { score: 65, next_action: 'demo', products: ['Plano Profissional'] },
    personId: 'ct1',
    conversationId: 'conv1',
    createdByType: 'nina',
    createdAt: '2026-07-01T09:12:00.000Z',
    source: 'ai',
  },
  {
    id: 'tl4',
    type: 'message',
    content: 'Novo contato via WhatsApp: "Boa tarde! Vi vocês no Instagram e tenho interesse em automatizar o atendimento..."',
    metadata: { channel: 'whatsapp' },
    personId: 'ct1',
    conversationId: 'conv1',
    createdByType: 'system',
    createdAt: '2026-07-01T09:12:00.000Z',
    channel: 'whatsapp',
    source: 'system',
  },
  {
    id: 'tl5',
    type: 'note',
    content: 'Cliente prefere contato pela manhã. Demo agendada para amanhã às 14h. Integração com ContaAzul é pré-requisito.',
    personId: 'ct1',
    dealId: 'dl1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-06-30T15:00:00.000Z',
    source: 'human',
  },
  {
    id: 'tl6',
    type: 'return',
    content: 'Demo agendada: Apresentação do Plano Profissional com integração ContaAzul',
    metadata: { date: daysFromNow(1), time: '14:00', type: 'demo' },
    personId: 'ct1',
    dealId: 'dl1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-06-30T14:30:00.000Z',
    source: 'human',
  },
  {
    id: 'tl7',
    type: 'important_change',
    content: 'Negócio criado: Automação de Atendimento — R$ 4.764',
    metadata: { value: 4764, priority: 'high' },
    personId: 'ct1',
    dealId: 'dl1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-06-25T10:00:00.000Z',
    source: 'human',
  },
  {
    id: 'tl8',
    type: 'message',
    content: 'Primeira mensagem recebida via Instagram',
    metadata: { channel: 'instagram' },
    personId: 'ct1',
    createdByType: 'system',
    createdAt: '2026-06-20T14:00:00.000Z',
    channel: 'instagram',
    source: 'system',
  },
];
