/**
 * Massa de dados fictícios para validação visual do CRM (Sprint 006.5 + Sprint 007).
 * O Workspace (conversas/contatos reais) não usa mais fallback mock — veja
 * useConversations.ts, que agora reflete o estado real do Supabase.
 */

import {
  Contact,
  Deal,
  Appointment,
  TeamMember,
  Person,
  Company,
  Task,
  TimelineEntry,
} from '@/types';

// ──────────────────────────────────────────────
// HELPERS
// ──────────────────────────────────────────────

const av = (name: string, bg = '0ea5e9'): string =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=fff`;

// ──────────────────────────────────────────────
// TEAM MEMBERS
// ──────────────────────────────────────────────

export const MOCK_TEAM_EXTENDED: TeamMember[] = [
  {
    id: 'tm1',
    name: 'Admin User',
    email: 'admin@integraconnect.com.br',
    role: 'admin',
    status: 'active',
    avatar: av('Admin User', '0891b2'),
    lastActive: 'Agora',
  },
  {
    id: 'tm2',
    name: 'Sarah Connor',
    email: 'sarah@integraconnect.com.br',
    role: 'manager',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?u=sarah_ic',
    lastActive: 'Há 3 min',
  },
  {
    id: 'tm3',
    name: 'Bruno Carvalho',
    email: 'bruno@integraconnect.com.br',
    role: 'agent',
    status: 'active',
    avatar: av('Bruno Carvalho', '7c3aed'),
    lastActive: 'Há 10 min',
  },
  {
    id: 'tm4',
    name: 'Patrícia Rocha',
    email: 'patricia@integraconnect.com.br',
    role: 'agent',
    status: 'active',
    avatar: av('Patricia Rocha', 'db2777'),
    lastActive: 'Há 22 min',
  },
  {
    id: 'tm5',
    name: 'Felipe Mendonça',
    email: 'felipe@integraconnect.com.br',
    role: 'agent',
    status: 'active',
    avatar: av('Felipe Mendonca', 'ea580c'),
    lastActive: 'Há 5 min',
  },
  {
    id: 'tm6',
    name: 'Carla Dias',
    email: 'carla@integraconnect.com.br',
    role: 'agent',
    status: 'active',
    avatar: av('Carla Dias', '16a34a'),
    lastActive: 'Há 45 min',
  },
];

// ──────────────────────────────────────────────
// CONTACTS (para a página de Contatos)
// ──────────────────────────────────────────────

export const MOCK_CONTACTS_EXTENDED: Contact[] = [
  { id: 'ct1', name: 'João Silva', phone: '+55 11 98432-1567', email: 'joao.silva@contabilidade.com.br', status: 'lead', lastContact: '01/07/2026' },
  { id: 'ct2', name: 'Maria Oliveira', phone: '+55 11 97654-3210', email: 'maria@oliveiracorp.com.br', status: 'customer', lastContact: '01/07/2026' },
  { id: 'ct3', name: 'Carlos Mendes', phone: '+55 11 96789-4532', email: 'carlosmendes@construtora.com.br', status: 'lead', lastContact: '01/07/2026' },
  { id: 'ct4', name: 'Fernanda Costa', phone: '+55 11 95678-2341', email: 'fernanda@costadvocacia.com.br', status: 'customer', lastContact: '30/06/2026' },
  { id: 'ct5', name: 'Pedro Santos', phone: '+55 11 94523-8765', email: 'pedro@santospremium.com.br', status: 'customer', lastContact: '01/07/2026' },
  { id: 'ct6', name: 'Clínica Vida Plena', phone: '+55 11 3456-7890', email: 'contato@vidaplena.med.br', status: 'lead', lastContact: '01/07/2026' },
  { id: 'ct7', name: 'Lumina Iluminação', phone: '+55 11 3234-5678', email: 'comercial@luminailuminacao.com.br', status: 'lead', lastContact: '29/06/2026' },
  { id: 'ct8', name: 'Ricardo Almeida', phone: '+55 11 93456-7890', email: 'ricardo.almeida@consultoria.com', status: 'customer', lastContact: '01/07/2026' },
  { id: 'ct9', name: 'Ana Souza', phone: '+55 11 92345-6789', email: 'ana.souza@minhaloja.com.br', status: 'lead', lastContact: '01/07/2026' },
  { id: 'ct10', name: 'Juliana Martins', phone: '+55 11 91234-5678', email: 'juliana@farmaciasunidas.com.br', status: 'lead', lastContact: '01/07/2026' },
];

// ──────────────────────────────────────────────
// DEALS (para o Kanban)
// ──────────────────────────────────────────────

export const MOCK_DEALS_EXTENDED: Deal[] = [
  {
    id: 'dl1',
    title: 'Automação de Atendimento',
    company: 'Contabilidade João Silva',
    value: 4764,
    stage: 'qualification',
    stageId: 'qualification',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Novo Lead', 'Contabilidade'],
    dueDate: '2026-07-05',
    priority: 'high',
    contactId: 'ct1',
    contactName: 'João Silva',
    contactPhone: '+55 11 98432-1567',
    contactEmail: 'joao.silva@contabilidade.com.br',
  },
  {
    id: 'dl2',
    title: 'Suporte Premium Anual',
    company: 'Oliveira Corp',
    value: 5964,
    stage: 'won',
    stageId: 'won',
    ownerAvatar: av('Bruno Carvalho', '7c3aed'),
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    tags: ['Cliente', 'Renovação'],
    priority: 'medium',
    contactId: 'ct2',
    contactName: 'Maria Oliveira',
    contactPhone: '+55 11 97654-3210',
    contactEmail: 'maria@oliveiracorp.com.br',
    wonAt: '2026-06-28T14:00:00.000Z',
  },
  {
    id: 'dl3',
    title: 'Plano Corporativo Business',
    company: 'Construtora Mendes',
    value: 19200,
    stage: 'negotiation',
    stageId: 'negotiation',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Enterprise', 'Hot Lead'],
    dueDate: '2026-07-10',
    priority: 'high',
    contactId: 'ct3',
    contactName: 'Carlos Mendes',
    contactPhone: '+55 11 96789-4532',
  },
  {
    id: 'dl4',
    title: 'Integração WhatsApp Business',
    company: 'Fernanda Costa Advocacia',
    value: 2388,
    stage: 'won',
    stageId: 'won',
    ownerAvatar: av('Carla Dias', '16a34a'),
    ownerId: 'tm6',
    ownerName: 'Carla Dias',
    tags: ['Jurídico', 'Onboarding'],
    priority: 'medium',
    contactId: 'ct4',
    contactName: 'Fernanda Costa',
    contactPhone: '+55 11 95678-2341',
    wonAt: '2026-06-30T09:41:00.000Z',
  },
  {
    id: 'dl5',
    title: 'Renovação Contrato VIP',
    company: 'Santos Premium Group',
    value: 14400,
    stage: 'negotiation',
    stageId: 'negotiation',
    ownerAvatar: av('Patricia Rocha', 'db2777'),
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    tags: ['VIP', 'Renovação', 'Em Risco'],
    dueDate: '2026-07-01',
    priority: 'high',
    contactId: 'ct5',
    contactName: 'Pedro Santos',
    contactPhone: '+55 11 94523-8765',
  },
  {
    id: 'dl6',
    title: 'Plano Saúde — Clínica Multidisciplinar',
    company: 'Clínica Vida Plena',
    value: 8964,
    stage: 'presentation',
    stageId: 'presentation',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Saúde', 'Demo Agendada'],
    dueDate: '2026-07-03',
    priority: 'medium',
    contactId: 'ct6',
    contactName: 'Clínica Vida Plena',
    contactPhone: '+55 11 3456-7890',
  },
  {
    id: 'dl7',
    title: 'Integração SAP + WhatsApp',
    company: 'Lumina Iluminação',
    value: 28800,
    stage: 'presentation',
    stageId: 'presentation',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Enterprise', 'SAP', 'Proposta Enviada'],
    dueDate: '2026-07-08',
    priority: 'high',
    contactId: 'ct7',
    contactName: 'Lumina Iluminação',
    contactPhone: '+55 11 3234-5678',
  },
  {
    id: 'dl8',
    title: 'Contrato de Retenção',
    company: 'Ricardo Almeida Consultoria',
    value: 3588,
    stage: 'negotiation',
    stageId: 'negotiation',
    ownerAvatar: av('Patricia Rocha', 'db2777'),
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    tags: ['Retenção', 'Urgente'],
    dueDate: '2026-07-15',
    priority: 'high',
    contactId: 'ct8',
    contactName: 'Ricardo Almeida',
    contactPhone: '+55 11 93456-7890',
  },
  {
    id: 'dl9',
    title: 'Plano Starter — E-commerce',
    company: 'Ana Souza — Minha Loja',
    value: 2364,
    stage: 'qualification',
    stageId: 'qualification',
    ownerAvatar: av('Bruno Carvalho', '7c3aed'),
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    tags: ['E-commerce', 'Lead Frio'],
    dueDate: '2026-07-20',
    priority: 'low',
    contactId: 'ct9',
    contactName: 'Ana Souza',
    contactPhone: '+55 11 92345-6789',
  },
  {
    id: 'dl10',
    title: 'Plano Multi-Unidade — 8 Farmácias',
    company: 'Farmácias Unidas Martins',
    value: 33600,
    stage: 'negotiation',
    stageId: 'negotiation',
    ownerAvatar: av('Felipe Mendonca', 'ea580c'),
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    tags: ['Enterprise', 'Hot Lead', 'Indicação'],
    dueDate: '2026-07-01',
    priority: 'high',
    contactId: 'ct10',
    contactName: 'Juliana Martins',
    contactPhone: '+55 11 91234-5678',
  },
  {
    id: 'dl11',
    title: 'Chatbot IA — Imobiliária',
    company: 'Imóveis Central SP',
    value: 7188,
    stage: 'new',
    stageId: 'new',
    ownerAvatar: av('Bruno Carvalho', '7c3aed'),
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    tags: ['Imobiliário', 'Novo'],
    dueDate: '2026-07-25',
    priority: 'medium',
    contactName: 'Rafael Nunes',
    contactPhone: '+55 11 98765-4321',
  },
  {
    id: 'dl12',
    title: 'Automação Financeira',
    company: 'Fintech Crédito Rápido',
    value: 15600,
    stage: 'lost',
    stageId: 'lost',
    ownerAvatar: av('Carla Dias', '16a34a'),
    ownerId: 'tm6',
    ownerName: 'Carla Dias',
    tags: ['Fintech', 'Perdido'],
    priority: 'medium',
    contactName: 'Marcos Figueiredo',
    lostAt: '2026-06-25T16:00:00.000Z',
    lostReason: 'Optou por solução concorrente com maior integração bancária.',
  },
];

// ──────────────────────────────────────────────
// APPOINTMENTS
// ──────────────────────────────────────────────

const today = new Date();
const dy = (offset: number) =>
  new Date(today.getFullYear(), today.getMonth(), today.getDate() + offset)
    .toISOString()
    .split('T')[0];

export const MOCK_APPOINTMENTS_EXTENDED: Appointment[] = [
  {
    id: 'ap1',
    title: 'Demo — Clínica Vida Plena',
    date: dy(2),
    time: '15:00',
    duration: 45,
    type: 'demo',
    attendees: ['Gerente Médico', 'TI Clínica', 'Recepcionista Chefe'],
    description: 'Apresentar módulo de agendamento automático e integração com prontuário eletrônico.',
    contact_id: 'ct6',
  },
  {
    id: 'ap2',
    title: 'Follow-up — Carlos Mendes',
    date: dy(1),
    time: '15:00',
    duration: 30,
    type: 'followup',
    attendees: ['Carlos Mendes'],
    description: 'Aguardando aprovação da diretoria para o Plano Business. Verificar decisão.',
    contact_id: 'ct3',
  },
  {
    id: 'ap3',
    title: 'Reunião de Kickoff — Fernanda Costa Advocacia',
    date: dy(3),
    time: '10:00',
    duration: 60,
    type: 'meeting',
    attendees: ['Fernanda Costa', 'Carla Dias'],
    description: 'Onboarding oficial — configurar fluxos de atendimento e treinar equipe.',
    contact_id: 'ct4',
  },
  {
    id: 'ap4',
    title: 'Demo — João Silva',
    date: dy(1),
    time: '14:00',
    duration: 60,
    type: 'demo',
    attendees: ['João Silva'],
    description: 'Demonstração do Plano Profissional com integração ContaAzul.',
    contact_id: 'ct1',
  },
  {
    id: 'ap5',
    title: 'Reunião de Fechamento — Lumina Iluminação',
    date: dy(7),
    time: '14:00',
    duration: 60,
    type: 'meeting',
    attendees: ['Diretor Comercial', 'TI Lumina', 'Felipe Mendonça'],
    description: 'Apresentar contrato ajustado com SLA 99,9% e relatório por departamento.',
    contact_id: 'ct7',
  },
  {
    id: 'ap6',
    title: 'Check-in Retenção — Ricardo Almeida',
    date: dy(0),
    time: '11:00',
    duration: 20,
    type: 'followup',
    attendees: ['Ricardo Almeida', 'Patrícia Rocha'],
    description: 'Monitoramento diário após compromisso de 15 dias de experiência sem erros.',
    contact_id: 'ct8',
  },
  {
    id: 'ap7',
    title: 'Negociação Final — Farmácias Unidas',
    date: dy(0),
    time: '16:00',
    duration: 45,
    type: 'meeting',
    attendees: ['Juliana Martins', 'Felipe Mendonça', 'Sarah Connor'],
    description: 'Decisão final sobre desconto de 15% no plano anual para 8 unidades.',
    contact_id: 'ct10',
  },
];

// ──────────────────────────────────────────────
// CRM — PESSOAS (Sprint 007)
// ──────────────────────────────────────────────

export const MOCK_PEOPLE: Person[] = [
  {
    id: 'ct1',
    name: 'João Silva',
    company: 'Contabilidade João Silva',
    companyId: 'comp1',
    document: '123.456.789-00',
    email: 'joao.silva@contabilidade.com.br',
    phones: ['+55 11 98432-1567'],
    whatsapp: '+55 11 98432-1567',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    origin: 'Instagram',
    tags: ['Novo Lead', 'Contabilidade', 'Demo Agendada'],
    notes: 'Cliente prefere contato pela manhã. Demo agendada para amanhã às 14h. Integração com ContaAzul é pré-requisito.',
    status: 'lead',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-01T09:30:00.000Z',
    // Sprint 008 — unified history example: same customer, three messaging
    // channels linked to this single Person, never duplicated.
    channelIdentities: [
      { channel: 'whatsapp', externalId: '+5511984321567', externalLabel: '+55 11 98432-1567', linkedAt: '2026-06-01T08:00:00.000Z' },
      { channel: 'instagram', externalId: 'joao.silva.ig', externalLabel: '@joao.silva.ig', linkedAt: '2026-06-20T14:00:00.000Z' },
      { channel: 'webchat', externalId: 'webchat-session-ct1', linkedAt: '2026-07-01T09:00:00.000Z' },
    ],
  },
  {
    id: 'ct2',
    name: 'Maria Oliveira',
    company: 'Oliveira Corp',
    companyId: 'comp2',
    document: '987.654.321-00',
    email: 'maria@oliveiracorp.com.br',
    phones: ['+55 11 97654-3210'],
    whatsapp: '+55 11 97654-3210',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    origin: 'Indicação',
    tags: ['Cliente', 'Renovação', 'VIP'],
    notes: 'Configurar renovação automática de token de WhatsApp Business a cada 90 dias.',
    status: 'customer',
    createdAt: '2025-03-15T08:00:00.000Z',
    updatedAt: '2026-07-01T08:45:00.000Z',
  },
  {
    id: 'ct3',
    name: 'Carlos Mendes',
    company: 'Construtora Mendes',
    companyId: 'comp3',
    document: '12.345.678/0001-90',
    email: 'carlosmendes@construtora.com.br',
    phones: ['+55 11 96789-4532', '+55 11 3123-4567'],
    whatsapp: '+55 11 96789-4532',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    origin: 'Google Ads',
    tags: ['Enterprise', 'Hot Lead', 'Negociação'],
    notes: 'Sempre solicitar aprovação interna antes de gerar contrato. Reunião de fechamento agendada para quinta.',
    status: 'lead',
    createdAt: '2026-05-10T08:00:00.000Z',
    updatedAt: '2026-07-01T07:55:00.000Z',
  },
  {
    id: 'ct4',
    name: 'Fernanda Costa',
    company: 'Fernanda Costa Advocacia',
    companyId: 'comp4',
    document: '456.789.012-00',
    email: 'fernanda@costadvocacia.com.br',
    phones: ['+55 11 95678-2341'],
    whatsapp: '+55 11 95678-2341',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm6',
    ownerName: 'Carla Dias',
    origin: 'LinkedIn',
    tags: ['Jurídico', 'Onboarding', 'Cliente VIP'],
    notes: 'Onboarding concluído. Tags configuradas. Kickoff agendado para revisão de fluxos.',
    status: 'customer',
    createdAt: '2026-04-20T08:00:00.000Z',
    updatedAt: '2026-06-30T09:41:00.000Z',
  },
  {
    id: 'ct5',
    name: 'Pedro Santos',
    company: 'Santos Premium Group',
    companyId: 'comp5',
    document: '789.012.345-00',
    email: 'pedro@santospremium.com.br',
    phones: ['+55 11 94523-8765'],
    whatsapp: '+55 11 94523-8765',
    city: 'Campinas',
    state: 'SP',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    origin: 'Indicação',
    tags: ['VIP', 'Em Risco', 'SLA Vencido'],
    notes: 'URGENTE — Cliente VIP há 2 anos. Cobrado indevidamente. Escalar para gerência imediatamente.',
    status: 'customer',
    createdAt: '2024-06-01T08:00:00.000Z',
    updatedAt: '2026-07-01T09:10:00.000Z',
  },
  {
    id: 'ct8',
    name: 'Ricardo Almeida',
    company: 'Ricardo Almeida Consultoria',
    companyId: 'comp6',
    document: '321.654.987-00',
    email: 'ricardo.almeida@consultoria.com',
    phones: ['+55 11 93456-7890'],
    whatsapp: '+55 11 93456-7890',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    origin: 'Referência',
    tags: ['Cancelamento', 'Retenção', 'Urgente'],
    notes: 'Compensação aprovada: 2 meses grátis + consultoria 2h. Prazo de 15 dias para provar melhoria.',
    status: 'customer',
    createdAt: '2025-01-10T08:00:00.000Z',
    updatedAt: '2026-07-01T08:58:00.000Z',
  },
  {
    id: 'ct9',
    name: 'Ana Souza',
    email: 'ana.souza@minhaloja.com.br',
    phones: ['+55 11 92345-6789'],
    whatsapp: '+55 11 92345-6789',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    origin: 'Instagram Ads',
    tags: ['Lead', 'E-commerce', 'Prospecto'],
    status: 'lead',
    createdAt: '2026-06-28T08:00:00.000Z',
    updatedAt: '2026-07-01T08:19:00.000Z',
  },
  {
    id: 'ct10',
    name: 'Juliana Martins',
    company: 'Farmácias Unidas Martins',
    companyId: 'comp7',
    document: '98.765.432/0001-10',
    email: 'juliana@farmaciasunidas.com.br',
    phones: ['+55 11 91234-5678', '+55 11 3456-0000'],
    whatsapp: '+55 11 91234-5678',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    origin: 'Indicação — Carlos Mendes',
    tags: ['Negociação', 'Hot Lead', 'Enterprise'],
    notes: 'Indicação do Carlos Mendes. 8 farmácias com IA customizada por filial. Orçamento da diretoria: R$ 2.800/mês.',
    status: 'lead',
    createdAt: '2026-06-25T08:00:00.000Z',
    updatedAt: '2026-07-01T09:50:00.000Z',
  },
];

// ──────────────────────────────────────────────
// CRM — EMPRESAS (Sprint 007)
// ──────────────────────────────────────────────

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp1',
    razaoSocial: 'João Silva Contabilidade ME',
    nomeFantasia: 'Contabilidade João Silva',
    cnpj: '12.345.678/0001-00',
    segmento: 'Contabilidade',
    porte: 'pequena',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.contabilidadejoaosilva.com.br',
    notes: 'Escritório de contabilidade com foco em PMEs. 3 atendentes.',
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-07-01T09:30:00.000Z',
    contactIds: ['ct1'],
    dealIds: ['dl1'],
  },
  {
    id: 'comp2',
    razaoSocial: 'Oliveira Corp Ltda',
    nomeFantasia: 'Oliveira Corp',
    cnpj: '98.765.432/0001-00',
    segmento: 'Tecnologia',
    porte: 'media',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    website: 'www.oliveiracorp.com.br',
    notes: 'Cliente ativo. Renovação do contrato em outubro.',
    createdAt: '2025-03-15T08:00:00.000Z',
    updatedAt: '2026-07-01T08:45:00.000Z',
    contactIds: ['ct2'],
    dealIds: ['dl2'],
  },
  {
    id: 'comp3',
    razaoSocial: 'Construtora Mendes S.A.',
    nomeFantasia: 'Construtora Mendes',
    cnpj: '45.678.901/0001-00',
    segmento: 'Construção Civil',
    porte: 'grande',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.construtoraemendes.com.br',
    notes: 'Empresa com múltiplas unidades. Decisão corporativa.',
    createdAt: '2026-05-10T08:00:00.000Z',
    updatedAt: '2026-07-01T07:55:00.000Z',
    contactIds: ['ct3'],
    dealIds: ['dl3'],
  },
  {
    id: 'comp4',
    razaoSocial: 'Fernanda Costa Advocacia e Consultoria',
    nomeFantasia: 'Costa Advocacia',
    cnpj: '56.789.012/0001-00',
    segmento: 'Jurídico',
    porte: 'pequena',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm6',
    ownerName: 'Carla Dias',
    website: 'www.costadvocacia.com.br',
    createdAt: '2026-04-20T08:00:00.000Z',
    updatedAt: '2026-06-30T09:41:00.000Z',
    contactIds: ['ct4'],
    dealIds: ['dl4'],
  },
  {
    id: 'comp5',
    razaoSocial: 'Santos Premium Group Ltda',
    nomeFantasia: 'Santos Premium',
    cnpj: '67.890.123/0001-00',
    segmento: 'Comércio',
    porte: 'grande',
    city: 'Campinas',
    state: 'SP',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    website: 'www.santospremiumgroup.com.br',
    notes: 'Cliente VIP há 2 anos. Conta estratégica.',
    createdAt: '2024-06-01T08:00:00.000Z',
    updatedAt: '2026-07-01T09:10:00.000Z',
    contactIds: ['ct5'],
    dealIds: ['dl5'],
  },
  {
    id: 'comp6',
    razaoSocial: 'Ricardo Almeida Consultoria e Gestão ME',
    nomeFantasia: 'Almeida Consultoria',
    cnpj: '78.901.234/0001-00',
    segmento: 'Consultoria',
    porte: 'pequena',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    createdAt: '2025-01-10T08:00:00.000Z',
    updatedAt: '2026-07-01T08:58:00.000Z',
    contactIds: ['ct8'],
    dealIds: ['dl8'],
  },
  {
    id: 'comp7',
    razaoSocial: 'Farmácias Unidas Martins S.A.',
    nomeFantasia: 'Farmácias Unidas',
    cnpj: '89.012.345/0001-00',
    segmento: 'Farmácia / Saúde',
    porte: 'grande',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.farmaciasunidas.com.br',
    notes: '8 unidades. IA customizada por filial. Indicação do Carlos Mendes.',
    createdAt: '2026-06-25T08:00:00.000Z',
    updatedAt: '2026-07-01T09:50:00.000Z',
    contactIds: ['ct10'],
    dealIds: ['dl10'],
  },
  {
    id: 'comp8',
    razaoSocial: 'Clínica Vida Plena Serviços Médicos Ltda',
    nomeFantasia: 'Clínica Vida Plena',
    cnpj: '90.123.456/0001-00',
    segmento: 'Saúde',
    porte: 'media',
    city: 'São Paulo',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.clinicavidaplena.med.br',
    notes: '12 especialidades. Alto volume de agendamentos manuais.',
    createdAt: '2026-06-15T08:00:00.000Z',
    updatedAt: '2026-07-01T14:35:00.000Z',
    contactIds: ['ct6'],
    dealIds: ['dl6'],
  },
  {
    id: 'comp9',
    razaoSocial: 'Lumina Iluminação Comércio e Industria Ltda',
    nomeFantasia: 'Lumina Iluminação',
    cnpj: '01.234.567/0001-00',
    segmento: 'Indústria / Comércio',
    porte: 'grande',
    city: 'Guarulhos',
    state: 'SP',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    website: 'www.luminailuminacao.com.br',
    notes: 'Operação 24/7. Contrato pode ser em nome da holding. SLA 99,9% já nos termos.',
    createdAt: '2026-05-20T08:00:00.000Z',
    updatedAt: '2026-06-29T14:38:00.000Z',
    contactIds: ['ct7'],
    dealIds: ['dl7'],
  },
];

// ──────────────────────────────────────────────
// CRM — TAREFAS (Sprint 007)
// ──────────────────────────────────────────────

const todayISO = new Date().toISOString();
const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

export const MOCK_TASKS: Task[] = [
  {
    id: 'task1',
    title: 'Confirmar participação na demo amanhã às 14h',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(0),
    priority: 'high',
    status: 'pending',
    origin: 'conversation',
    originId: 'conv1',
    personId: 'ct1',
    personName: 'João Silva',
    dealId: 'dl1',
    dealTitle: 'Automação de Atendimento',
    companyId: 'comp1',
    companyName: 'Contabilidade João Silva',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task2',
    title: 'Enviar proposta revisada com SLA 99,9%',
    description: 'Incluir relatório por departamento sem custo extra e cláusula de holding.',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(1),
    priority: 'high',
    status: 'pending',
    origin: 'deal',
    originId: 'dl7',
    personId: 'ct7',
    personName: 'Lumina Iluminação',
    dealId: 'dl7',
    dealTitle: 'Integração SAP + WhatsApp',
    companyId: 'comp9',
    companyName: 'Lumina Iluminação',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task3',
    title: 'Obter aprovação da Sarah para 15% de desconto',
    description: 'Farmácias Unidas — orçamento aprovado R$ 2.800/mês. Proposta atual R$ 3.200.',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(0),
    priority: 'high',
    status: 'in_progress',
    origin: 'deal',
    originId: 'dl10',
    personId: 'ct10',
    personName: 'Juliana Martins',
    dealId: 'dl10',
    dealTitle: 'Plano Multi-Unidade — 8 Farmácias',
    companyId: 'comp7',
    companyName: 'Farmácias Unidas',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task4',
    title: 'Escalar estorno de Pedro Santos para gerência financeira',
    description: 'Estorno em atraso (8 dias úteis). Compensação: 1 mês gratuito já aprovado.',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    dueDate: daysFromNow(0),
    priority: 'high',
    status: 'pending',
    origin: 'conversation',
    originId: 'conv5',
    personId: 'ct5',
    personName: 'Pedro Santos',
    dealId: 'dl5',
    dealTitle: 'Renovação Contrato VIP',
    companyId: 'comp5',
    companyName: 'Santos Premium Group',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task5',
    title: 'Follow-up Carlos Mendes — reunião de fechamento quinta 15h',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(3),
    priority: 'medium',
    status: 'pending',
    origin: 'deal',
    originId: 'dl3',
    personId: 'ct3',
    personName: 'Carlos Mendes',
    dealId: 'dl3',
    dealTitle: 'Plano Corporativo Business',
    companyId: 'comp3',
    companyName: 'Construtora Mendes',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task6',
    title: 'Preparar demo clínica — agendamento automático + integração Tasy/MV Soul',
    description: 'Incluir dados de redução de no-show. Demo quinta às 15h.',
    ownerId: 'tm5',
    ownerName: 'Felipe Mendonça',
    dueDate: daysFromNow(2),
    priority: 'medium',
    status: 'in_progress',
    origin: 'deal',
    originId: 'dl6',
    personId: 'ct6',
    personName: 'Clínica Vida Plena',
    dealId: 'dl6',
    dealTitle: 'Plano Saúde — Clínica Multidisciplinar',
    companyId: 'comp8',
    companyName: 'Clínica Vida Plena',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task7',
    title: 'Enviar proposta Plano Starter para Ana Souza',
    description: 'Foco em e-commerce. Destacar Black Friday como case de uso.',
    ownerId: 'tm3',
    ownerName: 'Bruno Carvalho',
    dueDate: daysFromNow(1),
    priority: 'low',
    status: 'pending',
    origin: 'conversation',
    originId: 'conv9',
    personId: 'ct9',
    personName: 'Ana Souza',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
  {
    id: 'task8',
    title: 'Monitoramento diário Ricardo Almeida — verificar qualidade IA',
    description: 'Prazo: 15 dias. Enviar relatório de qualidade semanal.',
    ownerId: 'tm4',
    ownerName: 'Patrícia Rocha',
    dueDate: daysFromNow(15),
    priority: 'medium',
    status: 'in_progress',
    origin: 'person',
    originId: 'ct8',
    personId: 'ct8',
    personName: 'Ricardo Almeida',
    dealId: 'dl8',
    dealTitle: 'Contrato de Retenção',
    companyId: 'comp6',
    companyName: 'Almeida Consultoria',
    createdAt: todayISO,
    updatedAt: todayISO,
  },
];

// ──────────────────────────────────────────────
// CRM — TIMELINE (Sprint 007)
// ──────────────────────────────────────────────

export const MOCK_TIMELINE_ENTRIES: TimelineEntry[] = [
  {
    id: 'tl1',
    type: 'stage_change',
    content: 'Negócio movido para Qualificação',
    metadata: { from: 'Novo Lead', to: 'Qualificação', dealTitle: 'Automação de Atendimento' },
    personId: 'ct1',
    dealId: 'dl1',
    conversationId: 'conv1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-07-01T09:15:00.000Z',
    source: 'human',
  },
  {
    id: 'tl2',
    type: 'task',
    content: 'Tarefa criada: Confirmar participação na demo às 14h',
    metadata: { taskId: 'task1', priority: 'high' },
    personId: 'ct1',
    dealId: 'dl1',
    taskId: 'task1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-07-01T09:00:00.000Z',
    source: 'human',
  },
  {
    id: 'tl3',
    type: 'ai_action',
    content: 'Nina qualificou o lead: score 65/100',
    metadata: { score: 65, next_action: 'demo', products: ['Plano Profissional'] },
    personId: 'ct1',
    conversationId: 'conv1',
    createdByType: 'nina',
    createdAt: '2026-07-01T09:12:00.000Z',
    source: 'ai',
  },
  {
    id: 'tl4',
    type: 'message',
    content: 'Novo contato via WhatsApp: "Boa tarde! Vi vocês no Instagram e tenho interesse em automatizar o atendimento..."',
    metadata: { channel: 'whatsapp' },
    personId: 'ct1',
    conversationId: 'conv1',
    createdByType: 'system',
    createdAt: '2026-07-01T09:12:00.000Z',
    channel: 'whatsapp',
    source: 'system',
  },
  {
    id: 'tl5',
    type: 'note',
    content: 'Cliente prefere contato pela manhã. Demo agendada para amanhã às 14h. Integração com ContaAzul é pré-requisito.',
    personId: 'ct1',
    dealId: 'dl1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-06-30T15:00:00.000Z',
    source: 'human',
  },
  {
    id: 'tl6',
    type: 'return',
    content: 'Demo agendada: Apresentação do Plano Profissional com integração ContaAzul',
    metadata: { date: daysFromNow(1), time: '14:00', type: 'demo' },
    personId: 'ct1',
    dealId: 'dl1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-06-30T14:30:00.000Z',
    source: 'human',
  },
  {
    id: 'tl7',
    type: 'important_change',
    content: 'Negócio criado: Automação de Atendimento — R$ 4.764',
    metadata: { value: 4764, priority: 'high' },
    personId: 'ct1',
    dealId: 'dl1',
    createdByType: 'human',
    createdByName: 'Felipe Mendonça',
    createdAt: '2026-06-25T10:00:00.000Z',
    source: 'human',
  },
  {
    id: 'tl8',
    type: 'message',
    content: 'Primeira mensagem recebida via Instagram',
    metadata: { channel: 'instagram' },
    personId: 'ct1',
    createdByType: 'system',
    createdAt: '2026-06-20T14:00:00.000Z',
    channel: 'instagram',
    source: 'system',
  },
];
